In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("ex1.csv")

In [3]:
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [4]:
!cat ex2.csv

1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [5]:
pd.read_csv("ex2.csv",header=None)

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [6]:
pd.read_csv("ex2.csv",names=["a","b","c","d","message"])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [7]:
names = ["a", "b", "c", "d", "message"]

In [8]:
pd.read_csv("ex2.csv",names=names,index_col="message")

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [9]:
!cat csv_mindex.csv

key1,key2,value1,value2
one,a,1,2
one,b,3,4
one,c,5,6
one,d,7,8
two,a,9,10
two,b,11,12
two,c,13,14
two,d,15,16

In [10]:
parsed=pd.read_csv("csv_mindex.csv",index_col=["key1","key2"])

In [11]:
!cat ex3.txt

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [12]:
result=pd.read_csv("ex3.txt",sep="\s+")

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipython-input-1874529820.py:1: SyntaxWarning: invalid escape sequence '\s'
  result=pd.read_csv("ex3.txt",sep="\s+")

In [13]:
result

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [14]:
!cat ex4.csv

# hey!
a,b,c,d,message
# just wanted to make things more difficult for you
# who reads CSV files with computers, anyway?
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [15]:
pd.read_csv("ex4.csv",skiprows=[0,2,3])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [16]:
!cat ex5.csv

something,a,b,c,d,message
one,1,2,3,4,NA
two,5,6,,8,world
three,9,10,11,12,foo

In [17]:
result=pd.read_csv("ex5.csv")

In [18]:
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [19]:
result.isna()

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [20]:
result=pd.read_csv("ex5.csv",na_values=["NULL"])

In [21]:
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [22]:
result2=pd.read_csv("ex5.csv",keep_default_na=False)

In [23]:
result2

  something  a   b   c   d message
0       one  1   2   3   4      NA
1       two  5   6       8   world
2     three  9  10  11  12     foo

In [24]:
result2.isna()

   something      a      b      c      d  message
0      False  False  False  False  False    False
1      False  False  False  False  False    False
2      False  False  False  False  False    False

In [25]:
result3=pd.read_csv("ex5.csv",keep_default_na=False,na_values=["NA"])

In [26]:
result3

  something  a   b   c   d message
0       one  1   2   3   4     NaN
1       two  5   6       8   world
2     three  9  10  11  12     foo

In [27]:
result3.isna()

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False  False  False    False
2      False  False  False  False  False    False

In [28]:
sentinels={"message":["foo","NA"],"something":["two"]}

In [29]:
pd.read_csv("ex5.csv",na_values=sentinels,keep_default_na=False)

  something  a   b   c   d message
0       one  1   2   3   4     NaN
1       NaN  5   6       8   world
2     three  9  10  11  12     NaN

In [30]:
pd.options.display.max_rows=10

In [31]:
result=pd.read_csv("ex6.csv")

In [32]:
result

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [33]:
pd.read_csv("ex6.csv",nrows=5)

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [34]:
chunker=pd.read_csv("ex6.csv",chunksize=1000)

In [35]:
type(chunker)

pandas.io.parsers.readers.TextFileReader

In [36]:
chunker=pd.read_csv("ex6.csv",chunksize=1000)

In [37]:
tot=pd.Series([],dtype="int64")
for piece in chunker:
  tot=tot.add(piece["key"].value_counts(),fill_value=0)

tot=tot.sort_values(ascending=False)

In [38]:
tot[:10]

key
E    368.0
X    364.0
L    346.0
O    343.0
Q    340.0
M    338.0
J    337.0
F    335.0
K    334.0
H    330.0
dtype: float64

In [39]:
data=pd.read_csv("ex5.csv")

In [40]:
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [41]:
data.to_csv("out.csv")

In [42]:
!cat out.csv

,something,a,b,c,d,message
0,one,1,2,3.0,4,
1,two,5,6,,8,world
2,three,9,10,11.0,12,foo

In [43]:
import sys

In [44]:
data.to_csv(sys.stdout,sep="|")

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo

In [45]:
data.to_csv(sys.stdout,na_rep="NULL")

,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,foo

In [46]:
data.to_csv(sys.stdout,index=False,header=False)

one,1,2,3.0,4,
two,5,6,,8,world
three,9,10,11.0,12,foo

In [47]:
data.to_csv(sys.stdout,index=False,columns=["a","b","c"])

a,b,c
1,2,3.0
5,6,
9,10,11.0

In [48]:
!cat ex7.csv

"a","b","c"
"1","2","3"
"1","2","3"

In [49]:
import csv

In [50]:
f=open("ex7.csv")

In [51]:
reader=csv.reader(f)

In [52]:
for line in reader:
  print(line)

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

In [53]:
f.close()

In [54]:
with open("ex7.csv") as f:
  lines=list(csv.reader(f))

In [55]:
header,values=lines[0],lines[1:]

In [56]:
data_dict={h: v for h,v in zip(header,zip(*values))}

In [57]:
data_dict

{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

In [58]:
obj = """
{"name": "Wes",
"cities_lived": ["Akron", "Nashville", "New York", "San Francisco"],
"pet": null,
"siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]},
{"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]
}
"""

In [59]:
import json

In [60]:
result=json.loads(obj)

In [61]:
result

{'name': 'Wes',
 'cities_lived': ['Akron', 'Nashville', 'New York', 'San Francisco'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 34, 'hobbies': ['guitars', 'soccer']},
  {'name': 'Katie', 'age': 42, 'hobbies': ['diving', 'art']}]}

In [62]:
ajson=json.dumps(result)

In [63]:
ajson

'{"name": "Wes", "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"], "pet": null, "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]}, {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]}'

In [64]:
siblings=pd.DataFrame(result["siblings"],columns=["name","age"])

In [65]:
siblings

    name  age
0  Scott   34
1  Katie   42

In [66]:
result["siblings"]

[{'name': 'Scott', 'age': 34, 'hobbies': ['guitars', 'soccer']},
 {'name': 'Katie', 'age': 42, 'hobbies': ['diving', 'art']}]

In [67]:
!cat example.json

[{"a": 1, "b": 2, "c": 3},
 {"a": 4, "b": 5, "c": 6},
 {"a": 7, "b": 8, "c": 9}]

In [68]:
data=pd.read_json("example.json")

In [69]:
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [71]:
data.to_json(sys.stdout)

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}

In [72]:
data.to_json(sys.stdout,orient="records")

[{"a":1,"b":2,"c":3},{"a":4,"b":5,"c":6},{"a":7,"b":8,"c":9}]

In [1]:
!pip install -q condacolab
import condacolab
condacolab.install()

⏬ Downloading https://github.com/jaimergp/miniforge/releases/download/24.11.2-1_colab/Miniforge3-colab-24.11.2-1_colab-Linux-x86_64.sh...
📦 Installing...
📌 Adjusting configuration...
🩹 Patching environment...
⏲ Done in 0:00:09
🔁 Restarting kernel...

In [1]:
!conda install lxml beautifulsoup4 html5lib

Channels:
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ done
Solving environment: / - done

## Package Plan ##

  environment location: /usr/local

  added / updated specs:
    - beautifulsoup4
    - html5lib
    - lxml


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    beautifulsoup4-4.13.5      |     pyha770c72_0          86 KB  conda-forge
    ca-certificates-2025.8.3   |       hbd8a1cb_0         151 KB  conda-forge
    certifi-2025.8.3           |     pyhd8ed1ab_0         155 KB  conda-forge
    conda-24.11.3              |  py311h38be061_0         1.1 MB  conda-forge
    html5lib-1.1               |     pyhd8ed1ab_2          93 KB  conda-forge
    libiconv-1.18              |       h3b78370_2         772 KB  conda-forge
    liblzma-5.8.1              |       hb9d3cd8_2         110 KB  conda-forge
    libxml2-2.13.8             |       h2cb61b6_1         681 KB  conda-forge
    libxslt-1.1.43             |       h7a3aeb2_0         239 KB  conda-forge
    lxml-6.0.1                 |  py311hc53b721_0         1.5 MB  conda-forge
    openssl-3.5.2              |       h26f9b46_0         3.0 MB  conda-forge
    six-1.17.0                 |     pyhe01879c_1          18 KB  conda-forge
    soupsieve-2.8              |     pyhd8ed1ab_0          37 KB  conda-forge
    typing-extensions-4.15.0   |       h396c80c_0          89 KB  conda-forge
    typing_extensions-4.15.0   |     pyhcf101f3_0          50 KB  conda-forge
    webencodings-0.5.1         |     pyhd8ed1ab_3          15 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         8.1 MB

The following NEW packages will be INSTALLED:

  beautifulsoup4     conda-forge/noarch::beautifulsoup4-4.13.5-pyha770c72_0
  html5lib           conda-forge/noarch::html5lib-1.1-pyhd8ed1ab_2
  libxslt            conda-forge/linux-64::libxslt-1.1.43-h7a3aeb2_0
  lxml               conda-forge/linux-64::lxml-6.0.1-py311hc53b721_0
  six                conda-forge/noarch::six-1.17.0-pyhe01879c_1
  soupsieve          conda-forge/noarch::soupsieve-2.8-pyhd8ed1ab_0
  typing-extensions  conda-forge/noarch::typing-extensions-4.15.0-h396c80c_0
  typing_extensions  conda-forge/noarch::typing_extensions-4.15.0-pyhcf101f3_0
  webencodings       conda-forge/noarch::webencodings-0.5.1-pyhd8ed1ab_3

The following packages will be UPDATED:

  ca-certificates    conda-forge/linux-64::ca-certificates~ --> conda-forge/noarch::ca-certificates-2025.8.3-hbd8a1cb_0
  certifi                           2024.12.14-pyhd8ed1ab_0 --> 2025.8.3-pyhd8ed1ab_0
  conda                             24.11.2-py311h38be061_1 --> 24.11.3-py311h38be061_0
  libiconv                                  1.17-hd590300_2 --> 1.18-h3b78370_2
  liblzma                                  5.6.3-hb9d3cd8_1 --> 5.8.1-hb9d3cd8_2
  libxml2                                 2.13.5-h0d44e9d_1 --> 2.13.8-h2cb61b6_1
  openssl                                  3.4.0-h7b32b05_1 --> 3.5.2-h26f9b46_0



Downloading and Extracting Packages:
openssl-3.5.2        | 3.0 MB    | :   0% 0/1 [00:00<?, ?it/s]
lxml-6.0.1           | 1.5 MB    | :   0% 0/1 [00:00<?, ?it/s]

conda-24.11.3        | 1.1 MB    | :   0% 0/1 [00:00<?, ?it/s]


libiconv-1.18        | 772 KB    | :   0% 0/1 [00:00<?, ?it/s]



libxml2-2.13.8       | 681 KB    | :   0% 0/1 [00:00<?, ?it/s]




libxslt-1.1.43       | 239 KB    | :   0% 0/1 [00:00<?, ?it/s]





certifi-2025.8.3     | 155 KB    | :   0% 0/1 [00:00<?, ?it/s]






ca-certificates-2025 | 151 KB    | :   0% 0/1 [00:00<?, ?it/s]







liblzma-5.8.1        | 110 KB    | :   0% 0/1 [00:00<?, ?it/s]








html5lib-1.1         | 93 KB     | :   0% 0/1 [00:00<?, ?it/s]









typing-extensions-4. | 89 KB     | :   0% 0/1 [00:00<?, ?it/s]










beautifulsoup4-4.13. | 86 KB     | :   0% 0/1 [00:00<?, ?it/s]











typing_extensions-4. | 50 KB     | :   0% 0/1 [00:00<?, ?it/s]












soupsieve-2.8        | 37 KB     | :   0% 0/1 [00:00<?, ?it/s]













six-1.17.0           | 18 KB     | :   0% 0/1 [00:00<?, ?it/s]














openssl-3.5.2        | 3.0 MB    | :   1% 0.005236433740607962/1 [00:00<00:19, 19.83s/it]
lxml-6.0.1           | 1.5 MB    | :   2% 0.02046106073066118/1 [00:00<00:05,  5.22s/it]


libiconv-1.18        | 772 KB    | :   2% 0.02073462114769368/1 [00:00<00:04,  4.95s/it]



libxml2-2.13.8       | 681 KB    | :   2% 0.023505781756621043/1 [00:00<00:04,  4.50s/it]

conda-24.11.3        | 1.1 MB    | :   1% 0.01364371451460054/1 [00:00<00:08,  8.74s/it]


libiconv-1.18        | 772 KB    | : 100% 1.0/1 [00:00<00:00,  4.95s/it]



libxml2-2.13.8       | 681 KB    | : 100% 1.0/1 [00:00<00:00,  4.50s/it]
lxml-6.0.1           | 1.5 MB    | : 100% 1.0/1 [00:00<00:00,  5.22s/it]

openssl-3.5.2        | 3.0 MB    | :  95% 0.9477945070500411/1 [00:00<00:00,  5.17it/s]





certifi-2025.8.3     | 155 KB    | :  10% 0.10324401986237491/1 [00:00<00:01,  2.07s/it]




libxslt-1.1.43       | 239 KB    | :   7% 0.06703791750375411/1 [00:00<00:02,  3.20s/it]





certifi-2025.8.3     | 155 KB    | : 100% 1.0/1 [00:00<00:00,  2.07s/it]




libxslt-1.1.43       | 239 KB    | : 100% 1.0/1 [00:00<00:00,  3.20s/it]







liblzma-5.8.1        | 110 KB    | :  15% 0.1451272875440679/1 [00:00<00:01,  1.60s/it]







openssl-3.5.2        | 3.0 MB    | : 100% 1.0/1 [00:00<00:00,  5.17it/s]






ca-certificates-2025 | 151 KB    | :  11% 0.10611261512156578/1 [00:00<00:02,  2.41s/it]






ca-certificates-2025 | 151 KB    | : 100% 1.0/1 [00:00<00:00,  2.41s/it]








html5lib-1.1         | 93 KB     | :  17% 0.17273043551600897/1 [00:00<00:01,  1.54s/it]








html5lib-1.1         | 93 KB     | : 100% 1.0/1 [00:00<00:00,  1.54s/it]









typing-extensions-4. | 89 KB     | :  18% 0.17928936454263922/1 [00:00<00:01,  1.54s/it]









typing-extensions-4. | 89 KB     | : 100% 1.0/1 [00:00<00:00,  1.54s/it]










beautifulsoup4-4.13. | 86 KB     | :  19% 0.18559550510886064/1 [00:00<00:01,  1.54s/it]










beautifulsoup4-4.13. | 86 KB     | : 100% 1.0/1 [00:00<00:00,  1.54s/it]


libiconv-1.18        | 772 KB    | : 100% 1.0/1 [00:00<00:00,  3.76it/s]


libiconv-1.18        | 772 KB    | : 100% 1.0/1 [00:00<00:00,  3.76it/s]













six-1.17.0           | 18 KB     | :  89% 0.8877810891357356/1 [00:00<00:00,  2.87it/s]













six-1.17.0           | 18 KB     | : 100% 1.0/1 [00:00<00:00,  2.87it/s]











typing_extensions-4. | 50 KB     | :  32% 0.3169542675849261/1 [00:00<00:00,  1.01it/s]











typing_extensions-4. | 50 KB     | : 100% 1.0/1 [00:00<00:00,  1.01it/s]



libxml2-2.13.8       | 681 KB    | : 100% 1.0/1 [00:00<00:00,  3.47it/s]



libxml2-2.13.8       | 681 KB    | : 100% 1.0/1 [00:00<00:00,  3.47it/s]












soupsieve-2.8        | 37 KB     | :  43% 0.43340475623627756/1 [00:00<00:00,  1.31it/s]












soupsieve-2.8        | 37 KB     | : 100% 1.0/1 [00:00<00:00,  1.31it/s]














webencodings-0.5.1   | 15 KB     | : 100% 1.0/1 [00:00<00:00,  2.71it/s]














webencodings-0.5.1   | 15 KB     | : 100% 1.0/1 [00:00<00:00,  2.71it/s]
lxml-6.0.1           | 1.5 MB    | : 100% 1.0/1 [00:00<00:00,  2.41it/s]
lxml-6.0.1           | 1.5 MB    | : 100% 1.0/1 [00:00<00:00,  2.41it/s]





certifi-2025.8.3     | 155 KB    | : 100% 1.0/1 [00:00<00:00,  2.48it/s]





certifi-2025.8.3     | 155 KB    | : 100% 1.0/1 [00:00<00:00,  2.48it/s]




libxslt-1.1.43       | 239 KB    | : 100% 1.0/1 [00:00<00:00,  2.08it/s]




libxslt-1.1.43       | 239 KB    | : 100% 1.0/1 [00:00<00:00,  2.08it/s]







liblzma-5.8.1        | 110 KB    | : 100% 1.0/1 [00:00<00:00,  1.96it/s]







liblzma-5.8.1        | 110 KB    | : 100% 1.0/1 [00:00<00:00,  1.96it/s]

conda-24.11.3        | 1.1 MB    | : 100% 1.0/1 [00:00<00:00,  1.54it/s]

conda-24.11.3        | 1.1 MB    | : 100% 1.0/1 [00:00<00:00,  1.54it/s]






ca-certificates-2025 | 151 KB    | : 100% 1.0/1 [00:00<00:00,  1.55it/s]






ca-certificates-2025 | 151 KB    | : 100% 1.0/1 [00:00<00:00,  1.55it/s]








html5lib-1.1         | 93 KB     | : 100% 1.0/1 [00:00<00:00,  1.43it/s]








html5lib-1.1         | 93 KB     | : 100% 1.0/1 [00:00<00:00,  1.43it/s]









typing-extensions-4. | 89 KB     | : 100% 1.0/1 [00:00<00:00,  1.42it/s]









openssl-3.5.2        | 3.0 MB    | : 100% 1.0/1 [00:00<00:00,  5.17it/s]










beautifulsoup4-4.13. | 86 KB     | : 100% 1.0/1 [00:00<00:00,  1.35it/s]










beautifulsoup4-4.13. | 86 KB     | : 100% 1.0/1 [00:00<00:00,  1.35it/s]













six-1.17.0           | 18 KB     | : 100% 1.0/1 [00:00<00:00,  2.87it/s]











typing_extensions-4. | 50 KB     | : 100% 1.0/1 [00:00<00:00,  1.28it/s]











typing_extensions-4. | 50 KB     | : 100% 1.0/1 [00:00<00:00,  1.28it/s]












soupsieve-2.8        | 37 KB     | : 100% 1.0/1 [00:00<00:00,  1.21it/s]












soupsieve-2.8        | 37 KB     | : 100% 1.0/1 [00:00<00:00,  1.21it/s]







































































































































Preparing transaction: - done
Verifying transaction: | / done
Executing transaction: \ | / - \ | / - \ | / done

In [2]:
!conda install numpy pandas

Channels:
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): - \ | / - \ | done
Solving environment: - \ | done


==> WARNING: A newer version of conda exists. <==
    current version: 24.11.3
    latest version: 25.7.0

Please update conda by running

    $ conda update -n base -c conda-forge conda



## Package Plan ##

  environment location: /usr/local

  added / updated specs:
    - numpy
    - pandas


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libblas-3.9.0              |31_h59b9bed_openblas          16 KB  conda-forge
    libcblas-3.9.0             |31_he106b2a_openblas          16 KB  conda-forge
    libgfortran-14.2.0         |       h69a702a_2          52 KB  conda-forge
    libgfortran5-14.2.0        |       hf1ad2bd_2         1.4 MB  conda-forge
    liblapack-3.9.0            |31_h7ac8fdf_openblas          16 KB  conda-forge
    libopenblas-0.3.29         |pthreads_h94d23a6_0         5.6 MB  conda-forge
    numpy-2.3.2                |  py311h2e04523_2         9.0 MB  conda-forge
    pandas-2.3.2               |  py311hed34c8f_0        14.6 MB  conda-forge
    python-dateutil-2.9.0.post0|     pyhe01879c_2         228 KB  conda-forge
    python-tzdata-2025.2       |     pyhd8ed1ab_0         141 KB  conda-forge
    pytz-2025.2                |     pyhd8ed1ab_0         185 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        31.3 MB

The following NEW packages will be INSTALLED:

  libblas            conda-forge/linux-64::libblas-3.9.0-31_h59b9bed_openblas
  libcblas           conda-forge/linux-64::libcblas-3.9.0-31_he106b2a_openblas
  libgfortran        conda-forge/linux-64::libgfortran-14.2.0-h69a702a_2
  libgfortran5       conda-forge/linux-64::libgfortran5-14.2.0-hf1ad2bd_2
  liblapack          conda-forge/linux-64::liblapack-3.9.0-31_h7ac8fdf_openblas
  libopenblas        conda-forge/linux-64::libopenblas-0.3.29-pthreads_h94d23a6_0
  numpy              conda-forge/linux-64::numpy-2.3.2-py311h2e04523_2
  pandas             conda-forge/linux-64::pandas-2.3.2-py311hed34c8f_0
  python-dateutil    conda-forge/noarch::python-dateutil-2.9.0.post0-pyhe01879c_2
  python-tzdata      conda-forge/noarch::python-tzdata-2025.2-pyhd8ed1ab_0
  pytz               conda-forge/noarch::pytz-2025.2-pyhd8ed1ab_0



Downloading and Extracting Packages:
pandas-2.3.2         | 14.6 MB   | :   0% 0/1 [00:00<?, ?it/s]
numpy-2.3.2          | 9.0 MB    | :   0% 0/1 [00:00<?, ?it/s]

libopenblas-0.3.29   | 5.6 MB    | :   0% 0/1 [00:00<?, ?it/s]


libgfortran5-14.2.0  | 1.4 MB    | :   0% 0/1 [00:00<?, ?it/s]



python-dateutil-2.9. | 228 KB    | :   0% 0/1 [00:00<?, ?it/s]




pytz-2025.2          | 185 KB    | :   0% 0/1 [00:00<?, ?it/s]





python-tzdata-2025.2 | 141 KB    | :   0% 0/1 [00:00<?, ?it/s]






libgfortran-14.2.0   | 52 KB     | :   0% 0/1 [00:00<?, ?it/s]







libblas-3.9.0        | 16 KB     | :   0% 0/1 [00:00<?, ?it/s]








libcblas-3.9.0       | 16 KB     | :   0% 0/1 [00:00<?, ?it/s]









liblapack-3.9.0      | 16 KB     | :   0% 0/1 [00:00<?, ?it/s]

libopenblas-0.3.29   | 5.6 MB    | :   0% 0.0027679004637044184/1 [00:00<00:36, 36.13s/it]
numpy-2.3.2          | 9.0 MB    | :   0% 0.0017401520869982578/1 [00:00<00:57, 57.99s/it]



python-dateutil-2.9. | 228 KB    | :   7% 0.07022416527367023/1 [00:00<00:01,  1.45s/it]


pandas-2.3.2         | 14.6 MB   | :   0% 0.0010670515276994437/1 [00:00<02:06, 126.96s/it]



python-dateutil-2.9. | 228 KB    | : 100% 1.0/1 [00:00<00:00,  1.45s/it]



python-dateutil-2.9. | 228 KB    | : 100% 1.0/1 [00:00<00:00,  1.45s/it]




pytz-2025.2          | 185 KB    | :   9% 0.08668095124725551/1 [00:00<00:02,  2.22s/it]

libopenblas-0.3.29   | 5.6 MB    | :  35% 0.35152335889046116/1 [00:00<00:00,  2.06it/s]
numpy-2.3.2          | 9.0 MB    | :  26% 0.2558023567887439/1 [00:00<00:00,  1.50it/s]


libgfortran5-14.2.0  | 1.4 MB    | : 100% 1.0/1 [00:00<00:00, 11.17s/it]




pandas-2.3.2         | 14.6 MB   | :  22% 0.21767851165068652/1 [00:00<00:00,  1.11it/s]





python-tzdata-2025.2 | 141 KB    | :  11% 0.11365149833518313/1 [00:00<00:01,  2.22s/it]





python-tzdata-2025.2 | 141 KB    | : 100% 1.0/1 [00:00<00:00,  2.22s/it]






libgfortran-14.2.0   | 52 KB     | :  30% 0.30491504289728844/1 [00:00<00:00,  1.16it/s]






libgfortran-14.2.0   | 52 KB     | : 100% 1.0/1 [00:00<00:00,  1.16it/s]
numpy-2.3.2          | 9.0 MB    | :  62% 0.6229744471453763/1 [00:00<00:00,  2.49it/s]

libopenblas-0.3.29   | 5.6 MB    | :  85% 0.8525133428209609/1 [00:00<00:00,  3.40it/s]







libblas-3.9.0        | 16 KB     | :  97% 0.9718251379085355/1 [00:00<00:00,  3.11it/s]







libblas-3.9.0        | 16 KB     | : 100% 1.0/1 [00:00<00:00,  3.11it/s]








libcblas-3.9.0       | 16 KB     | :  98% 0.9754703500833531/1 [00:00<00:00,  3.08it/s]








pandas-2.3.2         | 14.6 MB   | :  44% 0.44496048705066804/1 [00:00<00:00,  1.59it/s]

libopenblas-0.3.29   | 5.6 MB    | : 100% 1.0/1 [00:00<00:00,  3.40it/s]









liblapack-3.9.0      | 16 KB     | :  98% 0.9758189398451459/1 [00:00<00:00,  2.59it/s]









liblapack-3.9.0      | 16 KB     | : 100% 1.0/1 [00:00<00:00,  2.59it/s]
numpy-2.3.2          | 9.0 MB    | : 100% 1.0/1 [00:00<00:00,  2.82it/s]
pandas-2.3.2         | 14.6 MB   | :  94% 0.9368712413201116/1 [00:00<00:00,  2.84it/s]


libgfortran5-14.2.0  | 1.4 MB    | : 100% 1.0/1 [00:00<00:00,  2.34it/s]


pandas-2.3.2         | 14.6 MB   | : 100% 1.0/1 [00:00<00:00,  2.84it/s]




pytz-2025.2          | 185 KB    | : 100% 1.0/1 [00:00<00:00,  1.55it/s]




pytz-2025.2          | 185 KB    | : 100% 1.0/1 [00:00<00:00,  1.55it/s]






libgfortran-14.2.0   | 52 KB     | : 100% 1.0/1 [00:00<00:00,  1.37it/s]






libgfortran-14.2.0   | 52 KB     | : 100% 1.0/1 [00:00<00:00,  1.37it/s]







libblas-3.9.0        | 16 KB     | : 100% 1.0/1 [00:00<00:00,  3.11it/s]








libcblas-3.9.0       | 16 KB     | : 100% 1.0/1 [00:00<00:00,  3.08it/s]





python-tzdata-2025.2 | 141 KB    | : 100% 1.0/1 [00:00<00:00,  1.26it/s]





python-tzdata-2025.2 | 141 KB    | : 100% 1.0/1 [00:00<00:00,  1.26it/s]









liblapack-3.9.0      | 16 KB     | : 100% 1.0/1 [00:00<00:00,  2.59it/s]

libopenblas-0.3.29   | 5.6 MB    | : 100% 1.0/1 [00:01<00:00,  3.40it/s]
























































Preparing transaction: - \ done
Verifying transaction: / - \ | / - done
Executing transaction: | / - \ | / - \ | / - \ | / - \ | done

In [3]:
import pandas as pd
import numpy as np

In [4]:
tables=pd.read_html("fdic_failed_bank_list.html")

In [5]:
len(tables)

1

In [6]:
failures=tables[0]

In [7]:
failures.head()

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016"
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016"
2,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,"May 6, 2016","September 6, 2016"
3,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,"April 29, 2016","September 6, 2016"
4,North Milwaukee State Bank,Milwaukee,WI,20364,First-Citizens Bank & Trust Company,"March 11, 2016","June 16, 2016"

In [8]:
close_timestamps=pd.to_datetime(failures['Closing Date'])

In [9]:
close_timestamps

0     2016-09-23
1     2016-08-19
2     2016-05-06
3     2016-04-29
4     2016-03-11
         ...
542   2001-07-27
543   2001-05-03
544   2001-02-02
545   2000-12-14
546   2000-10-13
Name: Closing Date, Length: 547, dtype: datetime64[ns]

In [10]:
close_timestamps.dt.year.value_counts()

Closing Date
2010    157
2009    140
2011     92
2012     51
2008     25
2013     24
2014     18
2002     11
2015      8
2016      5
2004      4
2001      4
2007      3
2003      3
2000      2
Name: count, dtype: int64

In [11]:
from lxml import objectify

In [12]:
path="/content/drive/MyDrive/Colab Notebooks/Data/examples_of_pydata_book/datasets/mta_perf/Performance_MNR.xml"

In [13]:
with open(path) as f:
  parsed=objectify.parse(f)

In [14]:
root=parsed.getroot()

In [15]:
data=[]

In [16]:
skip_fields = ["PARENT_SEQ", "INDICATOR_SEQ",
"DESIRED_CHANGE", "DECIMAL_PLACES"]
for elt in root.INDICATOR:
  el_data={}
  for child in elt.getchildren():
    if child.tag in skip_fields:
      continue
    el_data[child.tag]=child.pyval
  data.append(el_data)

In [17]:
data

[{'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2008,
  'PERIOD_MONTH': 1,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 95.0,
  'YTD_ACTUAL': 96.9,
  'MONTHLY_TARGET': 95.0,
  'MONTHLY_ACTUAL': 96.9},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2008,
  'PERIOD_MONTH': 2,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 95.0,
  'YTD_ACTUAL': 96.0,
  'MONTHLY_TARGET': 95.0,
  'MONTHLY_ACTUAL': 95.0},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2008,
  'PERIOD_MONTH': 3,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 95.0,
  'YTD_ACTUAL': 96.3,
  'MONTHLY_TARGET': 95.0,
  'MONTHLY_ACTUAL': 96.9},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2008,
  'PERIOD_MONTH': 4,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 95.0,
  'YTD_ACTUAL': 96.8,
  'MONTHLY_TARGET': 95.0,
  'MONTHLY_ACTUAL': 98.3},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2008,
  'PERIOD_MONTH': 5,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 95.0,
  'YTD_ACTUAL': 96.6,
  'MONTHLY_TARGET': 95.0,
  'MONTHLY_ACTUAL': 95.8},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2008,
  'PERIOD_MONTH': 6,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 95.0,
  'YTD_ACTUAL': 96.2,
  'MONTHLY_TARGET': 95.0,
  'MONTHLY_ACTUAL': 94.4},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2008,
  'PERIOD_MONTH': 7,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 95.0,
  'YTD_ACTUAL': 96.2,
  'MONTHLY_TARGET': 95.0,
  'MONTHLY_ACTUAL': 96.0},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2008,
  'PERIOD_MONTH': 8,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 95.0,
  'YTD_ACTUAL': 96.2,
  'MONTHLY_TARGET': 95.0,
  'MONTHLY_ACTUAL': 96.4},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2008,
  'PERIOD_MONTH': 9,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 95.0,
  'YTD_ACTUAL': 95.9,
  'MONTHLY_TARGET': 95.0,
  'MONTHLY_ACTUAL': 93.7},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2008,
  'PERIOD_MONTH': 10,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 95.0,
  'YTD_ACTUAL': 96.0,
  'MONTHLY_TARGET': 95.0,
  'MONTHLY_ACTUAL': 96.4},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2008,
  'PERIOD_MONTH': 11,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 95.0,
  'YTD_ACTUAL': 96.1,
  'MONTHLY_TARGET': 95.0,
  'MONTHLY_ACTUAL': 96.9},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2008,
  'PERIOD_MONTH': 12,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 95.0,
  'YTD_ACTUAL': 96.0,
  'MONTHLY_TARGET': 95.0,
  'MONTHLY_ACTUAL': 95.1},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2009,
  'PERIOD_MONTH': 1,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.2,
  'YTD_ACTUAL': 92.6,
  'MONTHLY_TARGET': 96.2,
  'MONTHLY_ACTUAL': 92.6},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2009,
  'PERIOD_MONTH': 2,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.2,
  'YTD_ACTUAL': 94.6,
  'MONTHLY_TARGET': 96.2,
  'MONTHLY_ACTUAL': 96.8},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2009,
  'PERIOD_MONTH': 3,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.2,
  'YTD_ACTUAL': 95.4,
  'MONTHLY_TARGET': 96.2,
  'MONTHLY_ACTUAL': 96.9},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2009,
  'PERIOD_MONTH': 4,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.2,
  'YTD_ACTUAL': 95.9,
  'MONTHLY_TARGET': 96.2,
  'MONTHLY_ACTUAL': 97.1},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2009,
  'PERIOD_MONTH': 5,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.2,
  'YTD_ACTUAL': 96.2,
  'MONTHLY_TARGET': 96.2,
  'MONTHLY_ACTUAL': 97.8},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2009,
  'PERIOD_MONTH': 6,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.2,
  'YTD_ACTUAL': 96.4,
  'MONTHLY_TARGET': 96.2,
  'MONTHLY_ACTUAL': 97.3},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2009,
  'PERIOD_MONTH': 7,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.2,
  'YTD_ACTUAL': 96.5,
  'MONTHLY_TARGET': 96.2,
  'MONTHLY_ACTUAL': 96.7},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2009,
  'PERIOD_MONTH': 8,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.2,
  'YTD_ACTUAL': 96.4,
  'MONTHLY_TARGET': 96.2,
  'MONTHLY_ACTUAL': 95.7},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2009,
  'PERIOD_MONTH': 9,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.2,
  'YTD_ACTUAL': 96.3,
  'MONTHLY_TARGET': 96.2,
  'MONTHLY_ACTUAL': 96.1},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2009,
  'PERIOD_MONTH': 10,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.2,
  'YTD_ACTUAL': 96.2,
  'MONTHLY_TARGET': 96.2,
  'MONTHLY_ACTUAL': 94.8},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2009,
  'PERIOD_MONTH': 11,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.2,
  'YTD_ACTUAL': 96.1,
  'MONTHLY_TARGET': 96.2,
  'MONTHLY_ACTUAL': 95.7},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2009,
  'PERIOD_MONTH': 12,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.2,
  'YTD_ACTUAL': 96.0,
  'MONTHLY_TARGET': 96.2,
  'MONTHLY_ACTUAL': 95.0},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2010,
  'PERIOD_MONTH': 1,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.3,
  'YTD_ACTUAL': 98.0,
  'MONTHLY_TARGET': 96.3,
  'MONTHLY_ACTUAL': 98.0},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2010,
  'PERIOD_MONTH': 2,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.3,
  'YTD_ACTUAL': 95.6,
  'MONTHLY_TARGET': 96.3,
  'MONTHLY_ACTUAL': 93.0},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2010,
  'PERIOD_MONTH': 3,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.3,
  'YTD_ACTUAL': 96.1,
  'MONTHLY_TARGET': 96.3,
  'MONTHLY_ACTUAL': 96.9},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2010,
  'PERIOD_MONTH': 4,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.3,
  'YTD_ACTUAL': 96.6,
  'MONTHLY_TARGET': 96.3,
  'MONTHLY_ACTUAL': 98.1},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2010,
  'PERIOD_MONTH': 5,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.3,
  'YTD_ACTUAL': 96.8,
  'MONTHLY_TARGET': 96.3,
  'MONTHLY_ACTUAL': 97.6},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2010,
  'PERIOD_MONTH': 6,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.3,
  'YTD_ACTUAL': 96.9,
  'MONTHLY_TARGET': 96.3,
  'MONTHLY_ACTUAL': 97.4},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2010,
  'PERIOD_MONTH': 7,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.3,
  'YTD_ACTUAL': 96.9,
  'MONTHLY_TARGET': 96.3,
  'MONTHLY_ACTUAL': 96.6},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2010,
  'PERIOD_MONTH': 8,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.3,
  'YTD_ACTUAL': 96.9,
  'MONTHLY_TARGET': 96.3,

In [18]:
perf=pd.DataFrame(data)

In [19]:
perf.head()

,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,PERIOD_YEAR,PERIOD_MONTH,CATEGORY,FREQUENCY,INDICATOR_UNIT,YTD_TARGET,YTD_ACTUAL,MONTHLY_TARGET,MONTHLY_ACTUAL
0,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,1,Service Indicators,M,%,95.0,96.9,95.0,96.9
1,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,2,Service Indicators,M,%,95.0,96.0,95.0,95.0
2,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,3,Service Indicators,M,%,95.0,96.3,95.0,96.9
3,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,4,Service Indicators,M,%,95.0,96.8,95.0,98.3
4,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,5,Service Indicators,M,%,95.0,96.6,95.0,95.8

In [20]:
perf2=pd.read_xml(path)

In [21]:
perf2.head()

,INDICATOR_SEQ,PARENT_SEQ,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,PERIOD_YEAR,PERIOD_MONTH,CATEGORY,FREQUENCY,DESIRED_CHANGE,INDICATOR_UNIT,DECIMAL_PLACES,YTD_TARGET,YTD_ACTUAL,MONTHLY_TARGET,MONTHLY_ACTUAL
0,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,1,Service Indicators,M,U,%,1,95.00,96.90,95.00,96.90
1,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,2,Service Indicators,M,U,%,1,95.00,96.00,95.00,95.00
2,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,3,Service Indicators,M,U,%,1,95.00,96.30,95.00,96.90
3,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,4,Service Indicators,M,U,%,1,95.00,96.80,95.00,98.30
4,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,5,Service Indicators,M,U,%,1,95.00,96.60,95.00,95.80

In [22]:
frame=pd.read_csv("ex1.csv")

In [23]:
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [24]:
frame.to_pickle("frame_pickle")

In [25]:
pd.read_pickle("frame_pickle")

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [26]:
!conda install openpyxl xlrd

Channels:
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): - \ | / - \ | / done
Solving environment: \ | / - done


==> WARNING: A newer version of conda exists. <==
    current version: 24.11.3
    latest version: 25.7.0

Please update conda by running

    $ conda update -n base -c conda-forge conda



## Package Plan ##

  environment location: /usr/local

  added / updated specs:
    - openpyxl
    - xlrd


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    et_xmlfile-2.0.0           |     pyhd8ed1ab_1          21 KB  conda-forge
    openpyxl-3.1.5             |  py311h50c5138_1         691 KB  conda-forge
    xlrd-2.0.2                 |     pyhd8ed1ab_0          91 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         804 KB

The following NEW packages will be INSTALLED:

  et_xmlfile         conda-forge/noarch::et_xmlfile-2.0.0-pyhd8ed1ab_1
  openpyxl           conda-forge/linux-64::openpyxl-3.1.5-py311h50c5138_1
  xlrd               conda-forge/noarch::xlrd-2.0.2-pyhd8ed1ab_0



Downloading and Extracting Packages:
openpyxl-3.1.5       | 691 KB    | :   0% 0/1 [00:00<?, ?it/s]
xlrd-2.0.2           | 91 KB     | :   0% 0/1 [00:00<?, ?it/s]

et_xmlfile-2.0.0     | 21 KB     | :   0% 0/1 [00:00<?, ?it/s]

et_xmlfile-2.0.0     | 21 KB     | : 100% 1.0/1 [00:00<00:00, 11.57it/s]

openpyxl-3.1.5       | 691 KB    | :   5% 0.04628418557743646/1 [00:00<00:02,  2.25s/it]
xlrd-2.0.2           | 91 KB     | :  35% 0.3498201150836438/1 [00:00<00:00,  3.21it/s]
xlrd-2.0.2           | 91 KB     | : 100% 1.0/1 [00:00<00:00,  3.21it/s]




Preparing transaction: - done
Verifying transaction: | done
Executing transaction: - \ | / - \ | / - done

In [27]:
xlsx=pd.ExcelFile("ex1.xlsx")

In [28]:
xlsx.sheet_names

['Sheet1']

In [29]:
xlsx

In [30]:
xlsx.parse(sheet_name="Sheet1")

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [31]:
xlsx.parse(sheet_name="Sheet1",index_col=0)

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [32]:
frame=pd.read_excel("ex1.xlsx",sheet_name="Sheet1")

In [33]:
frame

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [34]:
writer=pd.ExcelWriter("ex2.xlsx")

In [35]:
with pd.ExcelWriter("ex2.xlsx") as writer:
  frame.to_excel(writer,sheet_name="Sheet1")

In [36]:
frame.to_excel("ex2.xlsx")

In [37]:
!conda install pytables

Channels:
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): - \ | / - \ | / done
Solving environment: \ | / done


==> WARNING: A newer version of conda exists. <==
    current version: 24.11.3
    latest version: 25.7.0

Please update conda by running

    $ conda update -n base -c conda-forge conda



## Package Plan ##

  environment location: /usr/local

  added / updated specs:
    - pytables


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    blosc-1.21.6               |       he440d0b_1          47 KB  conda-forge
    c-blosc2-2.21.1            |       h4cfbee9_0         339 KB  conda-forge
    hdf5-1.14.6                |nompi_h2d575fe_101         3.5 MB  conda-forge
    libaec-1.1.4               |       h3f801dc_0          36 KB  conda-forge
    libcurl-8.14.1             |       h332b0f4_0         439 KB  conda-forge
    nomkl-1.0                  |       h5ca1d4c_0           4 KB  conda-forge
    numexpr-2.10.2             |py311h38b10cd_100         196 KB  conda-forge
    py-cpuinfo-9.0.0           |     pyhd8ed1ab_1          25 KB  conda-forge
    pytables-3.10.2            |  py311h144bb87_8         1.6 MB  conda-forge
    snappy-1.2.2               |       h03e3b7b_0          45 KB  conda-forge
    zlib-ng-2.2.5              |       hde8ca8f_0         108 KB  conda-forge
    zstandard-0.23.0           |  py311h49ec1c0_3         476 KB  conda-forge
    zstd-1.5.7                 |       hb8e6e7a_2         554 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         7.3 MB

The following NEW packages will be INSTALLED:

  blosc              conda-forge/linux-64::blosc-1.21.6-he440d0b_1
  c-blosc2           conda-forge/linux-64::c-blosc2-2.21.1-h4cfbee9_0
  hdf5               conda-forge/linux-64::hdf5-1.14.6-nompi_h2d575fe_101
  libaec             conda-forge/linux-64::libaec-1.1.4-h3f801dc_0
  nomkl              conda-forge/noarch::nomkl-1.0-h5ca1d4c_0
  numexpr            conda-forge/linux-64::numexpr-2.10.2-py311h38b10cd_100
  py-cpuinfo         conda-forge/noarch::py-cpuinfo-9.0.0-pyhd8ed1ab_1
  pytables           conda-forge/linux-64::pytables-3.10.2-py311h144bb87_8
  snappy             conda-forge/linux-64::snappy-1.2.2-h03e3b7b_0
  zlib-ng            conda-forge/linux-64::zlib-ng-2.2.5-hde8ca8f_0

The following packages will be UPDATED:

  libcurl                                 8.11.1-h332b0f4_0 --> 8.14.1-h332b0f4_0
  zstandard                          0.23.0-py311hbc35293_1 --> 0.23.0-py311h49ec1c0_3
  zstd                                     1.5.6-ha6fb4c9_0 --> 1.5.7-hb8e6e7a_2



Downloading and Extracting Packages:
hdf5-1.14.6          | 3.5 MB    | :   0% 0/1 [00:00<?, ?it/s]
pytables-3.10.2      | 1.6 MB    | :   0% 0/1 [00:00<?, ?it/s]

zstd-1.5.7           | 554 KB    | :   0% 0/1 [00:00<?, ?it/s]


zstandard-0.23.0     | 476 KB    | :   0% 0/1 [00:00<?, ?it/s]



libcurl-8.14.1       | 439 KB    | :   0% 0/1 [00:00<?, ?it/s]




c-blosc2-2.21.1      | 339 KB    | :   0% 0/1 [00:00<?, ?it/s]





numexpr-2.10.2       | 196 KB    | :   0% 0/1 [00:00<?, ?it/s]






zlib-ng-2.2.5        | 108 KB    | :   0% 0/1 [00:00<?, ?it/s]







blosc-1.21.6         | 47 KB     | :   0% 0/1 [00:00<?, ?it/s]








snappy-1.2.2         | 45 KB     | :   0% 0/1 [00:00<?, ?it/s]









libaec-1.1.4         | 36 KB     | :   0% 0/1 [00:00<?, ?it/s]










py-cpuinfo-9.0.0     | 25 KB     | :   0% 0/1 [00:00<?, ?it/s]











nomkl-1.0            | 4 KB      | :   0% 0/1 [00:00<?, ?it/s]


hdf5-1.14.6          | 3.5 MB    | :   0% 0.004438367935392273/1 [00:00<00:24, 24.23s/it]
pytables-3.10.2      | 1.6 MB    | :   1% 0.009717519351706705/1 [00:00<00:11, 11.61s/it]

zstd-1.5.7           | 554 KB    | :   3% 0.02886651702497278/1 [00:00<00:04,  4.37s/it]



libcurl-8.14.1       | 439 KB    | :   4% 0.03641617212331355/1 [00:00<00:03,  3.40s/it]


zstandard-0.23.0     | 476 KB    | : 100% 1.0/1 [00:00<00:00,  1.55s/it]

zstd-1.5.7           | 554 KB    | : 100% 1.0/1 [00:00<00:00,  4.37s/it]



libcurl-8.14.1       | 439 KB    | : 100% 1.0/1 [00:00<00:00,  3.40s/it]
pytables-3.10.2      | 1.6 MB    | : 100% 1.0/1 [00:00<00:00, 11.61s/it]




hdf5-1.14.6          | 3.5 MB    | :  75% 0.7545225490166864/1 [00:00<00:00,  4.27it/s]




c-blosc2-2.21.1      | 339 KB    | : 100% 1.0/1 [00:00<00:00,  4.14s/it]


zstandard-0.23.0     | 476 KB    | : 100% 1.0/1 [00:00<00:00,  5.15it/s]


zstandard-0.23.0     | 476 KB    | : 100% 1.0/1 [00:00<00:00,  5.15it/s]






zlib-ng-2.2.5        | 108 KB    | :  15% 0.14781267197748166/1 [00:00<00:01,  1.50s/it]





numexpr-2.10.2       | 196 KB    | :   8% 0.08168515517886077/1 [00:00<00:02,  2.74s/it]






zlib-ng-2.2.5        | 108 KB    | : 100% 1.0/1 [00:00<00:00,  1.50s/it]





hdf5-1.14.6          | 3.5 MB    | : 100% 1.0/1 [00:00<00:00,  4.27it/s]

zstd-1.5.7           | 554 KB    | : 100% 1.0/1 [00:00<00:00,  4.63it/s]

zstd-1.5.7           | 554 KB    | : 100% 1.0/1 [00:00<00:00,  4.63it/s]








snappy-1.2.2         | 45 KB     | :  36% 0.35769020849252264/1 [00:00<00:00,  1.41it/s]








snappy-1.2.2         | 45 KB     | : 100% 1.0/1 [00:00<00:00,  1.41it/s]



libcurl-8.14.1       | 439 KB    | : 100% 1.0/1 [00:00<00:00,  4.34it/s]



libcurl-8.14.1       | 439 KB    | : 100% 1.0/1 [00:00<00:00,  4.34it/s]









libaec-1.1.4         | 36 KB     | :  44% 0.4449151391717583/1 [00:00<00:00,  1.68it/s]









libaec-1.1.4         | 36 KB     | : 100% 1.0/1 [00:00<00:00,  1.68it/s]







blosc-1.21.6         | 47 KB     | :  34% 0.33832366241972456/1 [00:00<00:00,  1.19it/s]







blosc-1.21.6         | 47 KB     | : 100% 1.0/1 [00:00<00:00,  1.19it/s]










py-cpuinfo-9.0.0     | 25 KB     | :  64% 0.6358767367849103/1 [00:00<00:00,  2.24it/s]










py-cpuinfo-9.0.0     | 25 KB     | : 100% 1.0/1 [00:00<00:00,  2.24it/s]











nomkl-1.0            | 4 KB      | : 100% 1.0/1 [00:00<00:00,  3.43it/s]











nomkl-1.0            | 4 KB      | : 100% 1.0/1 [00:00<00:00,  3.43it/s]




c-blosc2-2.21.1      | 339 KB    | : 100% 1.0/1 [00:00<00:00,  4.04it/s]




c-blosc2-2.21.1      | 339 KB    | : 100% 1.0/1 [00:00<00:00,  4.04it/s]






zlib-ng-2.2.5        | 108 KB    | : 100% 1.0/1 [00:00<00:00,  1.50s/it]





numexpr-2.10.2       | 196 KB    | : 100% 1.0/1 [00:00<00:00,  3.42it/s]





numexpr-2.10.2       | 196 KB    | : 100% 1.0/1 [00:00<00:00,  3.42it/s]
pytables-3.10.2      | 1.6 MB    | : 100% 1.0/1 [00:00<00:00,  2.30it/s]
pytables-3.10.2      | 1.6 MB    | : 100% 1.0/1 [00:00<00:00,  2.30it/s]








snappy-1.2.2         | 45 KB     | : 100% 1.0/1 [00:00<00:00,  2.26it/s]








snappy-1.2.2         | 45 KB     | : 100% 1.0/1 [00:00<00:00,  2.26it/s]









libaec-1.1.4         | 36 KB     | : 100% 1.0/1 [00:00<00:00,  2.14it/s]









libaec-1.1.4         | 36 KB     | : 100% 1.0/1 [00:00<00:00,  2.14it/s]







blosc-1.21.6         | 47 KB     | : 100% 1.0/1 [00:00<00:00,  2.17it/s]







blosc-1.21.6         | 47 KB     | : 100% 1.0/1 [00:00<00:00,  2.17it/s]










py-cpuinfo-9.0.0     | 25 KB     | : 100% 1.0/1 [00:00<00:00,  1.89it/s]










py-cpuinfo-9.0.0     | 25 KB     | : 100% 1.0/1 [00:00<00:00,  1.89it/s]


























































































Preparing transaction: - done
Verifying transaction: | done
Executing transaction: - \ | / - \ | / - done

In [38]:
frame=pd.DataFrame({"a":np.random.standard_normal(100)})

In [39]:
store=pd.HDFStore("mydata.h5")

In [40]:
store

<class 'pandas.io.pytables.HDFStore'>
File path: mydata.h5

In [41]:
store["obj1"]=frame

In [42]:
store["obj1_col"]=frame["a"]

In [43]:
store

<class 'pandas.io.pytables.HDFStore'>
File path: mydata.h5

In [44]:
store["obj1"]

           a
0  -1.089217
1  -0.916122
2   0.462194
3   0.508741
4  -0.647409
..       ...
95  0.988240
96 -0.414903
97  0.253654
98 -0.430939
99  0.195977

[100 rows x 1 columns]

In [45]:
!conda install requests

Channels:
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): - \ | / - \ | / - \ | / done
Solving environment: \ | / done


==> WARNING: A newer version of conda exists. <==
    current version: 24.11.3
    latest version: 25.7.0

Please update conda by running

    $ conda update -n base -c conda-forge conda



## Package Plan ##

  environment location: /usr/local

  added / updated specs:
    - requests


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    requests-2.32.5            |     pyhd8ed1ab_0          58 KB  conda-forge
    ------------------------------------------------------------
                                           Total:          58 KB

The following packages will be UPDATED:

  requests                              2.32.3-pyhd8ed1ab_1 --> 2.32.5-pyhd8ed1ab_0



Downloading and Extracting Packages:

Preparing transaction: - done
Verifying transaction: | done
Executing transaction: - \ | / - \ | / - done

In [46]:
import requests

In [47]:
url="https://api.github.com/repos/pandas-dev/pandas/issues"

In [48]:
resp=requests.get(url)

In [49]:
resp.raise_for_status()

In [50]:
resp

In [52]:
data=resp.json()

In [53]:
data[0]["title"]

'ENH: keep the type option for keys in groupby'

In [54]:
issues=pd.DataFrame(data,columns=["number","title","labels","state"])

In [55]:
issues

,number,title,labels,state
0,62206,ENH: keep the type option for keys in groupby,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
1,62205,BUG: `record_prefix` ignored when `record_path...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
2,62204,BUG: memory leak in to_json when converting Da...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
3,62203,TST: Reduce banklist.html to make bs4 test run...,"[{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...",open
4,62200,BUG: Behavior change in pandas 3.x with `Serie...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
5,62198,BUG: Remove special-casing for date objects in...,[],open
6,62196,"BUG: divmod(pd.NA, s) returns single Series in...","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
7,62194,DOC: Clarify parameter rules in the Notes Sect...,[],open
8,62191,DOC: definition of a scalar in rich comparison...,[],open
9,62189,BUG: DataFrame.rank does not return EA types w...,[],open
10,62185,"DOC: NaT - ""alias of NaT""; NA - ""alias of <NA>""","[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...",open
11,62182,BUG: Fix ArrowDtype.itemsize for fixed-width t...,[],open
12,62178,CLN: Lint for usage of Deprecation/FutureWarning,[],open
13,62177,REF: use _cast_pointwise_result in map,[],open
14,62176,BUG: upgrade to PyQt6 to fix arm64 docker build,[],open
15,62175,BUG: Fix Index.get_level_values() mishandling ...,[],open
16,62174,BUG/TST: Series round with dtype object,[],open
17,62172,DOC: update the description for the 'docker bu...,[],open
18,62169,BUG: Index.get_level_values() does not handle ...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
19,62164,REF: use _cast_pointwise_result in map,[],open
20,62161,DOC: date_range/timedelta_range confusing 3 ou...,"[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...",open
21,62159,DEPR: .str accessor with object dtype,[],open
22,62158,API: indexing dates-with-datetime64,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
23,62157,BUG/API: comparison datetime64-vs-dates,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
24,62154,BUG: resampling with origin=end_date includes ...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
25,62150,BUG: Inconsistent behaviour when merging reset...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
26,62149,REF: get rid of StringArrayNumpySemantics,[],open
27,62146,BUG: Fails to Build on Raspberry Pi 3 (tested ...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
28,62145,fix enum typing from _lib,[],open
29,62144,BUG / API: setitem on pandas object fails if u...,"[{'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyM...",open

In [56]:
import sqlite3