In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({"key1" : ["a", "a", None, "b", "b", "a", None],
                   "key2" : pd.Series([1, 2, 1, 2, 1, None, 1], dtype="Int64"),
                   "data1" : np.random.standard_normal(7),
                   "data2" : np.random.standard_normal(7)})

In [3]:
df

   key1  key2     data1     data2
0     a     1  0.846828  1.203164
1     a     2 -1.138741 -0.257645
2  None     1 -1.684988 -0.891281
3     b     2 -0.254037  1.483781
4     b     1 -0.670809 -1.000682
5     a  <NA>  0.226029 -0.877950
6  None     1 -0.251125  1.002620

In [4]:
grouped = df["data1"].groupby(df["key1"])

In [5]:
grouped

In [6]:
grouped.mean()

key1
a   -0.021961
b   -0.462423
Name: data1, dtype: float64

In [7]:
means = df["data1"].groupby([df["key1"], df["key2"]]).mean()

In [8]:
means

key1  key2
a     1       0.846828
      2      -1.138741
b     1      -0.670809
      2      -0.254037
Name: data1, dtype: float64

In [9]:
means.unstack()

key2         1         2
key1
a     0.846828 -1.138741
b    -0.670809 -0.254037

In [10]:
states = np.array(["OH", "CA", "CA", "OH", "OH", "CA", "OH"])

In [11]:
years = [2005, 2005, 2006, 2005, 2006, 2005, 2006]

In [12]:
df["data1"].groupby([states, years]).mean()

CA  2005   -0.456356
    2006   -1.684988
OH  2005    0.296396
    2006   -0.460967
Name: data1, dtype: float64

In [13]:
df.groupby("key1").mean()

      key2     data1     data2
key1
a      1.5 -0.021961  0.022523
b      1.5 -0.462423  0.241550

In [14]:
df.iloc[:,1:4].groupby("key2").mean()

         data1     data2
key2
1    -0.440023  0.078455
2    -0.696389  0.613068

In [15]:
df.groupby(["key1", "key2"]).mean()

              data1     data2
key1 key2
a    1     0.846828  1.203164
     2    -1.138741 -0.257645
b    1    -0.670809 -1.000682
     2    -0.254037  1.483781

In [16]:
df.groupby(["key1","key2"]).size()

key1  key2
a     1       1
      2       1
b     1       1
      2       1
dtype: int64

In [17]:
df.groupby(["key1", "key2"], dropna=False).size()

key1  key2
a     1       1
      2       1
      <NA>    1
b     1       1
      2       1
NaN   1       2
dtype: int64

In [18]:
df.groupby("key1").count()

      key2  data1  data2
key1
a        2      3      3
b        2      2      2

In [19]:
for name, group in df.groupby("key1"):
  print(name)
  print(group)

a
  key1  key2     data1     data2
0    a     1  0.846828  1.203164
1    a     2 -1.138741 -0.257645
5    a  <NA>  0.226029 -0.877950
b
  key1  key2     data1     data2
3    b     2 -0.254037  1.483781
4    b     1 -0.670809 -1.000682

In [20]:
for (k1, k2) in df.groupby(["key1", "key2"]):
  print((k1, k2))
  print(group)

(('a', np.int64(1)),   key1  key2     data1     data2
0    a     1  0.846828  1.203164)
  key1  key2     data1     data2
3    b     2 -0.254037  1.483781
4    b     1 -0.670809 -1.000682
(('a', np.int64(2)),   key1  key2     data1     data2
1    a     2 -1.138741 -0.257645)
  key1  key2     data1     data2
3    b     2 -0.254037  1.483781
4    b     1 -0.670809 -1.000682
(('b', np.int64(1)),   key1  key2     data1     data2
4    b     1 -0.670809 -1.000682)
  key1  key2     data1     data2
3    b     2 -0.254037  1.483781
4    b     1 -0.670809 -1.000682
(('b', np.int64(2)),   key1  key2     data1     data2
3    b     2 -0.254037  1.483781)
  key1  key2     data1     data2
3    b     2 -0.254037  1.483781
4    b     1 -0.670809 -1.000682

In [21]:
pieces = {name: group for name, group in df.groupby("key1")}

In [22]:
pieces

{'a':   key1  key2     data1     data2
 0    a     1  0.846828  1.203164
 1    a     2 -1.138741 -0.257645
 5    a  <NA>  0.226029 -0.877950,
 'b':   key1  key2     data1     data2
 3    b     2 -0.254037  1.483781
 4    b     1 -0.670809 -1.000682}

In [23]:
grouped = df.groupby({"key1": "key", "key2": "key", "data1": "data", "data2": "data"}, axis="columns")

/tmp/ipython-input-2799057606.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  grouped = df.groupby({"key1": "key", "key2": "key", "data1": "data", "data2": "data"}, axis="columns")

In [24]:
for group_key, group_values in grouped:
  print(group_key)
  print(group_values)

data
      data1     data2
0  0.846828  1.203164
1 -1.138741 -0.257645
2 -1.684988 -0.891281
3 -0.254037  1.483781
4 -0.670809 -1.000682
5  0.226029 -0.877950
6 -0.251125  1.002620
key
   key1  key2
0     a     1
1     a     2
2  None     1
3     b     2
4     b     1
5     a  <NA>
6  None     1

In [25]:
df.groupby(["key1", "key2"])[["data2"]].mean()

              data2
key1 key2
a    1     1.203164
     2    -0.257645
b    1    -1.000682
     2     1.483781

In [26]:
s_grouped = df.groupby(["key1", "key2"])["data2"]

In [27]:
s_grouped

In [28]:
s_grouped.mean()

key1  key2
a     1       1.203164
      2      -0.257645
b     1      -1.000682
      2       1.483781
Name: data2, dtype: float64

In [29]:
people = pd.DataFrame(np.random.standard_normal((5, 5)),columns=["a", "b", "c", "d", "e"],index=["Joe", "Steve", "Wanda", "Jill", "Trey"])

In [30]:
people.iloc[2:3, [1, 2]] = np.nan # Add a few NA values

In [31]:
people

              a         b         c         d         e
Joe   -0.172023 -0.149815  0.959547  2.073112 -0.882092
Steve  0.278367  0.595239 -0.422240 -1.211208 -1.218253
Wanda -0.920934       NaN       NaN  0.123527  1.212178
Jill   0.412305 -0.230373  0.352747  2.496103  0.052840
Trey   0.770870  1.122075  0.107520 -1.175545  4.777144

In [32]:
mapping = {"a": "red", "b": "red", "c": "blue","d": "blue", "e": "red", "f" : "orange"}

In [33]:
by_column = people.groupby(mapping, axis="columns")

/tmp/ipython-input-2536829432.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  by_column = people.groupby(mapping, axis="columns")

In [34]:
by_column.sum()

           blue       red
Joe    3.032659 -1.203930
Steve -1.633448 -0.344647
Wanda  0.123527  0.291244
Jill   2.848850  0.234772
Trey  -1.068024  6.670088

In [35]:
map_series = pd.Series(mapping)

In [36]:
map_series

a       red
b       red
c      blue
d      blue
e       red
f    orange
dtype: object

In [37]:
people.groupby(map_series, axis="columns").count()

/tmp/ipython-input-2727320543.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  people.groupby(map_series, axis="columns").count()

       blue  red
Joe       2    3
Steve     2    3
Wanda     1    2
Jill      2    3
Trey      2    3

In [38]:
people.groupby(len).sum()

          a         b         c         d         e
3 -0.172023 -0.149815  0.959547  2.073112 -0.882092
4  1.183174  0.891701  0.460267  1.320559  4.829984
5 -0.642567  0.595239 -0.422240 -1.087681 -0.006076

In [39]:
people

              a         b         c         d         e
Joe   -0.172023 -0.149815  0.959547  2.073112 -0.882092
Steve  0.278367  0.595239 -0.422240 -1.211208 -1.218253
Wanda -0.920934       NaN       NaN  0.123527  1.212178
Jill   0.412305 -0.230373  0.352747  2.496103  0.052840
Trey   0.770870  1.122075  0.107520 -1.175545  4.777144

In [40]:
key_list = ["one", "one", "one", "two", "two"]

In [41]:
people.groupby([len, key_list]).min()

              a         b         c         d         e
3 one -0.172023 -0.149815  0.959547  2.073112 -0.882092
4 two  0.412305 -0.230373  0.107520 -1.175545  0.052840
5 one -0.920934  0.595239 -0.422240 -1.211208 -1.218253

In [42]:
columns = pd.MultiIndex.from_arrays([["US", "US", "US", "JP", "JP"],[1, 3, 5, 1, 3]],names=["cty", "tenor"])

In [43]:
hier_df = pd.DataFrame(np.random.standard_normal((4, 5)), columns=columns)

In [44]:
hier_df

cty          US                            JP
tenor         1         3         5         1         3
0      1.841984  0.676225  0.555387  1.552128 -0.191575
1      0.647396  1.370138  1.043474  0.820841 -1.662514
2      0.781523  0.071435  0.801944  2.193870  1.030982
3     -0.921963 -1.219554  0.451248 -0.576278  0.676102

In [45]:
hier_df.groupby(level="cty", axis="columns").count()

/tmp/ipython-input-2795167867.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  hier_df.groupby(level="cty", axis="columns").count()

cty  JP  US
0     2   3
1     2   3
2     2   3
3     2   3

In [46]:
df

   key1  key2     data1     data2
0     a     1  0.846828  1.203164
1     a     2 -1.138741 -0.257645
2  None     1 -1.684988 -0.891281
3     b     2 -0.254037  1.483781
4     b     1 -0.670809 -1.000682
5     a  <NA>  0.226029 -0.877950
6  None     1 -0.251125  1.002620

In [47]:
grouped = df.groupby("key1")

In [48]:
grouped["data1"].nsmallest(2)

key1
a     1   -1.138741
      5    0.226029
b     4   -0.670809
      3   -0.254037
Name: data1, dtype: float64

In [49]:
def peak_to_peak(arr):
  return arr.max() - arr.min()

In [50]:
grouped.agg(peak_to_peak)

      key2     data1     data2
key1
a        1  1.985569  2.081114
b        1  0.416772  2.484463

In [51]:
grouped.describe()

      key2                                           data1            ...  \
     count mean       std  min   25%  50%   75%  max count      mean  ...
key1                                                                  ...
a      2.0  1.5  0.707107  1.0  1.25  1.5  1.75  2.0   3.0 -0.021961  ...
b      2.0  1.5  0.707107  1.0  1.25  1.5  1.75  2.0   2.0 -0.462423  ...

                         data2                                          \
           75%       max count      mean       std       min       25%
key1
a     0.536429  0.846828   3.0  0.022523  1.068471 -0.877950 -0.567797
b    -0.358230 -0.254037   2.0  0.241550  1.756780 -1.000682 -0.379566


           50%       75%       max
key1
a    -0.257645  0.472760  1.203164
b     0.241550  0.862665  1.483781

[2 rows x 24 columns]

In [52]:
tips = pd.read_csv("tips.csv")

In [53]:
tips.head()

   total_bill   tip smoker  day    time  size
0       16.99  1.01     No  Sun  Dinner     2
1       10.34  1.66     No  Sun  Dinner     3
2       21.01  3.50     No  Sun  Dinner     3
3       23.68  3.31     No  Sun  Dinner     2
4       24.59  3.61     No  Sun  Dinner     4

In [54]:
tips["tip_pct"] = tips["tip"] / tips["total_bill"]

In [55]:
tips.head()

   total_bill   tip smoker  day    time  size   tip_pct
0       16.99  1.01     No  Sun  Dinner     2  0.059447
1       10.34  1.66     No  Sun  Dinner     3  0.160542
2       21.01  3.50     No  Sun  Dinner     3  0.166587
3       23.68  3.31     No  Sun  Dinner     2  0.139780
4       24.59  3.61     No  Sun  Dinner     4  0.146808

In [56]:
grouped = tips.groupby(["day", "smoker"])

In [57]:
grouped_pct = grouped["tip_pct"]

In [58]:
grouped_pct.agg("mean")

day   smoker
Fri   No        0.151650
      Yes       0.174783
Sat   No        0.158048
      Yes       0.147906
Sun   No        0.160113
      Yes       0.187250
Thur  No        0.160298
      Yes       0.163863
Name: tip_pct, dtype: float64

In [59]:
grouped_pct.agg(["mean", "std", peak_to_peak])

                 mean       std  peak_to_peak
day  smoker
Fri  No      0.151650  0.028123      0.067349
     Yes     0.174783  0.051293      0.159925
Sat  No      0.158048  0.039767      0.235193
     Yes     0.147906  0.061375      0.290095
Sun  No      0.160113  0.042347      0.193226
     Yes     0.187250  0.154134      0.644685
Thur No      0.160298  0.038774      0.193350
     Yes     0.163863  0.039389      0.151240

In [60]:
grouped_pct.agg([("average", "mean"), ("stdev", np.std)])

/tmp/ipython-input-1734782830.py:1: FutureWarning: The provided callable <function std at 0x7bab90121da0> is currently using SeriesGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  grouped_pct.agg([("average", "mean"), ("stdev", np.std)])

              average     stdev
day  smoker
Fri  No      0.151650  0.028123
     Yes     0.174783  0.051293
Sat  No      0.158048  0.039767
     Yes     0.147906  0.061375
Sun  No      0.160113  0.042347
     Yes     0.187250  0.154134
Thur No      0.160298  0.038774
     Yes     0.163863  0.039389

In [61]:
functions = ["count", "mean", "max"]

In [62]:
result = grouped[["tip_pct", "total_bill"]].agg(functions)

In [63]:
result

            tip_pct                     total_bill
              count      mean       max      count       mean    max
day  smoker
Fri  No           4  0.151650  0.187735          4  18.420000  22.75
     Yes         15  0.174783  0.263480         15  16.813333  40.17
Sat  No          45  0.158048  0.291990         45  19.661778  48.33
     Yes         42  0.147906  0.325733         42  21.276667  50.81
Sun  No          57  0.160113  0.252672         57  20.506667  48.17
     Yes         19  0.187250  0.710345         19  24.120000  45.35
Thur No          45  0.160298  0.266312         45  17.113111  41.19
     Yes         17  0.163863  0.241255         17  19.190588  43.11

In [64]:
result["tip_pct"]

             count      mean       max
day  smoker
Fri  No          4  0.151650  0.187735
     Yes        15  0.174783  0.263480
Sat  No         45  0.158048  0.291990
     Yes        42  0.147906  0.325733
Sun  No         57  0.160113  0.252672
     Yes        19  0.187250  0.710345
Thur No         45  0.160298  0.266312
     Yes        17  0.163863  0.241255

In [65]:
ftuples = [("Average", "mean"), ("Variance", np.var)]

In [66]:
grouped[["tip_pct", "total_bill"]].agg(ftuples)

/tmp/ipython-input-365474927.py:1: FutureWarning: The provided callable <function var at 0x7bab90121ee0> is currently using SeriesGroupBy.var. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "var" instead.
  grouped[["tip_pct", "total_bill"]].agg(ftuples)

              tip_pct           total_bill
              Average  Variance    Average    Variance
day  smoker
Fri  No      0.151650  0.000791  18.420000   25.596333
     Yes     0.174783  0.002631  16.813333   82.562438
Sat  No      0.158048  0.001581  19.661778   79.908965
     Yes     0.147906  0.003767  21.276667  101.387535
Sun  No      0.160113  0.001793  20.506667   66.099980
     Yes     0.187250  0.023757  24.120000  109.046044
Thur No      0.160298  0.001503  17.113111   59.625081
     Yes     0.163863  0.001551  19.190588   69.808518

In [67]:
grouped.agg({"tip": np.max, "size": "sum"})

/tmp/ipython-input-3453032214.py:1: FutureWarning: The provided callable <function max at 0x7bab90121260> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  grouped.agg({"tip": np.max, "size": "sum"})

               tip  size
day  smoker
Fri  No       3.50     9
     Yes      4.73    31
Sat  No       9.00   115
     Yes     10.00   104
Sun  No       6.00   167
     Yes      6.50    49
Thur No       6.70   112
     Yes      5.00    40

In [68]:
grouped.agg({"tip_pct": ["min", "max", "mean", "std"], "size": "sum"})

              tip_pct                               size
                  min       max      mean       std  sum
day  smoker
Fri  No      0.120385  0.187735  0.151650  0.028123    9
     Yes     0.103555  0.263480  0.174783  0.051293   31
Sat  No      0.056797  0.291990  0.158048  0.039767  115
     Yes     0.035638  0.325733  0.147906  0.061375  104
Sun  No      0.059447  0.252672  0.160113  0.042347  167
     Yes     0.065660  0.710345  0.187250  0.154134   49
Thur No      0.072961  0.266312  0.160298  0.038774  112
     Yes     0.090014  0.241255  0.163863  0.039389   40

In [69]:
tips

     total_bill   tip smoker   day    time  size   tip_pct
0         16.99  1.01     No   Sun  Dinner     2  0.059447
1         10.34  1.66     No   Sun  Dinner     3  0.160542
2         21.01  3.50     No   Sun  Dinner     3  0.166587
3         23.68  3.31     No   Sun  Dinner     2  0.139780
4         24.59  3.61     No   Sun  Dinner     4  0.146808
..          ...   ...    ...   ...     ...   ...       ...
239       29.03  5.92     No   Sat  Dinner     3  0.203927
240       27.18  2.00    Yes   Sat  Dinner     2  0.073584
241       22.67  2.00    Yes   Sat  Dinner     2  0.088222
242       17.82  1.75     No   Sat  Dinner     2  0.098204
243       18.78  3.00     No  Thur  Dinner     2  0.159744

[244 rows x 7 columns]

In [70]:
tips.drop("time", axis="columns").groupby(["day", "smoker"], as_index=False).mean()

    day smoker  total_bill       tip      size   tip_pct
0   Fri     No   18.420000  2.812500  2.250000  0.151650
1   Fri    Yes   16.813333  2.714000  2.066667  0.174783
2   Sat     No   19.661778  3.102889  2.555556  0.158048
3   Sat    Yes   21.276667  2.875476  2.476190  0.147906
4   Sun     No   20.506667  3.167895  2.929825  0.160113
5   Sun    Yes   24.120000  3.516842  2.578947  0.187250
6  Thur     No   17.113111  2.673778  2.488889  0.160298
7  Thur    Yes   19.190588  3.030000  2.352941  0.163863

In [75]:
def top(df, n=5, column="tip_pct"):
  return df.sort_values(column, ascending=False)[:n]

In [76]:
top(tips, n=6)

     total_bill   tip smoker  day    time  size   tip_pct
172        7.25  5.15    Yes  Sun  Dinner     2  0.710345
178        9.60  4.00    Yes  Sun  Dinner     2  0.416667
67         3.07  1.00    Yes  Sat  Dinner     1  0.325733
232       11.61  3.39     No  Sat  Dinner     2  0.291990
183       23.17  6.50    Yes  Sun  Dinner     4  0.280535
109       14.31  4.00    Yes  Sat  Dinner     2  0.279525

In [77]:
tips.groupby("smoker").apply(top)

/tmp/ipython-input-2530541573.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  tips.groupby("smoker").apply(top)

            total_bill   tip smoker   day    time  size   tip_pct
smoker
No     232       11.61  3.39     No   Sat  Dinner     2  0.291990
       149        7.51  2.00     No  Thur   Lunch     2  0.266312
       51        10.29  2.60     No   Sun  Dinner     2  0.252672
       185       20.69  5.00     No   Sun  Dinner     5  0.241663
       88        24.71  5.85     No  Thur   Lunch     2  0.236746
Yes    172        7.25  5.15    Yes   Sun  Dinner     2  0.710345
       178        9.60  4.00    Yes   Sun  Dinner     2  0.416667
       67         3.07  1.00    Yes   Sat  Dinner     1  0.325733
       183       23.17  6.50    Yes   Sun  Dinner     4  0.280535
       109       14.31  4.00    Yes   Sat  Dinner     2  0.279525

In [78]:
tips.groupby(["smoker", "day"]).apply(top, n=1, column="total_bill")

/tmp/ipython-input-643835440.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  tips.groupby(["smoker", "day"]).apply(top, n=1, column="total_bill")

                 total_bill    tip smoker   day    time  size   tip_pct
smoker day
No     Fri  94        22.75   3.25     No   Fri  Dinner     2  0.142857
       Sat  212       48.33   9.00     No   Sat  Dinner     4  0.186220
       Sun  156       48.17   5.00     No   Sun  Dinner     6  0.103799
       Thur 142       41.19   5.00     No  Thur   Lunch     5  0.121389
Yes    Fri  95        40.17   4.73    Yes   Fri  Dinner     4  0.117750
       Sat  170       50.81  10.00    Yes   Sat  Dinner     3  0.196812
       Sun  182       45.35   3.50    Yes   Sun  Dinner     3  0.077178
       Thur 197       43.11   5.00    Yes  Thur   Lunch     4  0.115982

In [79]:
result = tips.groupby("smoker")["tip_pct"].describe()

In [80]:
result

,count,mean,std,min,25%,50%,75%,max
smoker,,,,,,,,
No,151.0,0.159328,0.039910,0.056797,0.136906,0.155625,0.185014,0.291990
Yes,93.0,0.163196,0.085119,0.035638,0.106771,0.153846,0.195059,0.710345

In [81]:
result.unstack("smoker")

       smoker
count  No        151.000000
       Yes        93.000000
mean   No          0.159328
       Yes         0.163196
std    No          0.039910
       Yes         0.085119
min    No          0.056797
       Yes         0.035638
25%    No          0.136906
       Yes         0.106771
50%    No          0.155625
       Yes         0.153846
75%    No          0.185014
       Yes         0.195059
max    No          0.291990
       Yes         0.710345
dtype: float64

In [82]:
tips.groupby("smoker", group_keys=False).apply(top)

/tmp/ipython-input-3851957478.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  tips.groupby("smoker", group_keys=False).apply(top)

     total_bill   tip smoker   day    time  size   tip_pct
232       11.61  3.39     No   Sat  Dinner     2  0.291990
149        7.51  2.00     No  Thur   Lunch     2  0.266312
51        10.29  2.60     No   Sun  Dinner     2  0.252672
185       20.69  5.00     No   Sun  Dinner     5  0.241663
88        24.71  5.85     No  Thur   Lunch     2  0.236746
172        7.25  5.15    Yes   Sun  Dinner     2  0.710345
178        9.60  4.00    Yes   Sun  Dinner     2  0.416667
67         3.07  1.00    Yes   Sat  Dinner     1  0.325733
183       23.17  6.50    Yes   Sun  Dinner     4  0.280535
109       14.31  4.00    Yes   Sat  Dinner     2  0.279525

In [83]:
tips.groupby("smoker", group_keys=True).apply(top)

/tmp/ipython-input-1981216992.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  tips.groupby("smoker", group_keys=True).apply(top)

            total_bill   tip smoker   day    time  size   tip_pct
smoker
No     232       11.61  3.39     No   Sat  Dinner     2  0.291990
       149        7.51  2.00     No  Thur   Lunch     2  0.266312
       51        10.29  2.60     No   Sun  Dinner     2  0.252672
       185       20.69  5.00     No   Sun  Dinner     5  0.241663
       88        24.71  5.85     No  Thur   Lunch     2  0.236746
Yes    172        7.25  5.15    Yes   Sun  Dinner     2  0.710345
       178        9.60  4.00    Yes   Sun  Dinner     2  0.416667
       67         3.07  1.00    Yes   Sat  Dinner     1  0.325733
       183       23.17  6.50    Yes   Sun  Dinner     4  0.280535
       109       14.31  4.00    Yes   Sat  Dinner     2  0.279525

In [84]:
frame = pd.DataFrame({"data1": np.random.standard_normal(1000),"data2": np.random.standard_normal(1000)})

In [85]:
frame.head()

      data1     data2
0  0.814085  0.194165
1  0.093655  0.434807
2 -0.284912 -1.081189
3 -3.210772  1.000834
4 -0.003794 -0.142268

In [87]:
quartiles = pd.cut(frame["data1"], 4)

In [88]:
quartiles.head(10)

0       (0.209, 1.92]
1     (-1.501, 0.209]
2     (-1.501, 0.209]
3    (-3.218, -1.501]
4     (-1.501, 0.209]
5    (-3.218, -1.501]
6     (-1.501, 0.209]
7     (-1.501, 0.209]
8     (-1.501, 0.209]
9       (0.209, 1.92]
Name: data1, dtype: category
Categories (4, interval[float64, right]): [(-3.218, -1.501] < (-1.501, 0.209] < (0.209, 1.92] <
                                           (1.92, 3.63]]

In [90]:
def get_stats(group):
  return pd.DataFrame(
      {"min": group.min(), "max": group.max(),
      "count": group.count(), "mean": group.mean()}
  )

In [91]:
grouped = frame.groupby(quartiles)

/tmp/ipython-input-4041437760.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = frame.groupby(quartiles)

In [92]:
grouped.apply(get_stats)

                             min       max  count      mean
data1
(-3.218, -1.501] data1 -3.210772 -1.502482     68 -1.906900
                 data2 -2.473775  2.865189     68  0.076902
(-1.501, 0.209]  data1 -1.500562  0.206518    512 -0.521333
                 data2 -3.248161  3.633131    512  0.091210
(0.209, 1.92]    data1  0.209798  1.893416    397  0.853313
                 data2 -2.731840  2.336705    397  0.012779
(1.92, 3.63]     data1  1.985110  3.629717     23  2.346838
                 data2 -1.343278  1.799441     23  0.040316

In [93]:
grouped.agg(["min", "max", "count", "mean"])

                     data1                               data2            \
                       min       max count      mean       min       max
data1
(-3.218, -1.501] -3.210772 -1.502482    68 -1.906900 -2.473775  2.865189
(-1.501, 0.209]  -1.500562  0.206518   512 -0.521333 -3.248161  3.633131
(0.209, 1.92]     0.209798  1.893416   397  0.853313 -2.731840  2.336705
(1.92, 3.63]      1.985110  3.629717    23  2.346838 -1.343278  1.799441


                 count      mean
data1
(-3.218, -1.501]    68  0.076902
(-1.501, 0.209]    512  0.091210
(0.209, 1.92]      397  0.012779
(1.92, 3.63]        23  0.040316

In [95]:
grouped.agg("count")

                  data1  data2
data1
(-3.218, -1.501]     68     68
(-1.501, 0.209]     512    512
(0.209, 1.92]       397    397
(1.92, 3.63]         23     23

In [96]:
quartiles_samp = pd.qcut(frame["data1"], 4, labels=False)

In [97]:
quartiles_samp.head()

0    3
1    2
2    1
3    0
4    1
Name: data1, dtype: int64

In [98]:
grouped = frame.groupby(quartiles_samp)

In [99]:
grouped.apply(get_stats)

                  min       max  count      mean
data1
0     data1 -3.210772 -0.714503    250 -1.277460
      data2 -2.612998  3.136557    250  0.116854
1     data1 -0.710181  0.018334    250 -0.346599
      data2 -3.248161  3.633131    250  0.106472
2     data1  0.020297  0.682613    250  0.337760
      data2 -2.322945  3.196212    250 -0.038505
3     data1  0.684467  3.629717    250  1.270903
      data2 -2.731840  2.336705    250  0.046894

In [100]:
s = pd.Series(np.random.standard_normal(6))

In [101]:
s[::2] = np.nan

In [102]:
s

0         NaN
1   -0.030275
2         NaN
3    0.015347
4         NaN
5   -0.698418
dtype: float64

In [103]:
s.fillna(s.mean())

0   -0.237782
1   -0.030275
2   -0.237782
3    0.015347
4   -0.237782
5   -0.698418
dtype: float64

In [104]:
states = ["Ohio", "New York", "Vermont", "Florida","Oregon", "Nevada", "California", "Idaho"]

In [105]:
group_key = ["East", "East", "East", "East","West", "West", "West", "West"]

In [106]:
data = pd.Series(np.random.standard_normal(8), index=states)

In [107]:
data

Ohio         -0.217272
New York      1.352583
Vermont      -2.527483
Florida      -1.822446
Oregon        1.537728
Nevada        0.521034
California   -1.167014
Idaho        -0.900413
dtype: float64

In [108]:
data[["Vermont", "Nevada", "Idaho"]] = np.nan

In [109]:
data.groupby(group_key).size()

East    4
West    4
dtype: int64

In [110]:
data.groupby(group_key).count()

East    3
West    2
dtype: int64

In [111]:
data.groupby(group_key).mean()

East   -0.229045
West    0.185357
dtype: float64

In [112]:
def fill_mean(group):
  return group.fillna(group.mean())

In [113]:
data.groupby(group_key).apply(fill_mean)

East  Ohio         -0.217272
      New York      1.352583
      Vermont      -0.229045
      Florida      -1.822446
West  Oregon        1.537728
      Nevada        0.185357
      California   -1.167014
      Idaho         0.185357
dtype: float64

In [114]:
fill_values = {"East": 0.5, "West": -1}

In [115]:
def fill_func(group):
  return group.fillna(fill_values[group.name])

In [116]:
data.groupby(group_key).apply(fill_func)

East  Ohio         -0.217272
      New York      1.352583
      Vermont       0.500000
      Florida      -1.822446
West  Oregon        1.537728
      Nevada       -1.000000
      California   -1.167014
      Idaho        -1.000000
dtype: float64

In [118]:
suits = ["H", "S", "C", "D"] # Hearts, Spades, Clubs, Diamonds
card_val = (list(range(1, 11)) + [10] * 3) * 4
base_names = ["A"] + list(range(2, 11)) + ["J", "K", "Q"]
cards = []
for suit in suits:
  cards.extend(str(num) + suit for num in base_names)

deck = pd.Series(card_val, index=cards)

In [119]:
deck.head(13)

AH      1
2H      2
3H      3
4H      4
5H      5
6H      6
7H      7
8H      8
9H      9
10H    10
JH     10
KH     10
QH     10
dtype: int64

In [120]:
def draw(deck, n=5):
  return deck.sample(n)

In [121]:
draw(deck)

3S     3
9D     9
QD    10
4C     4
9H     9
dtype: int64

In [122]:
def get_suit(card):
  return card[-1]

In [124]:
deck.groupby(get_suit).apply(draw, n=2)

C  10C    10
   6C      6
D  JD     10
   QD     10
H  7H      7
   5H      5
S  3S      3
   10S    10
dtype: int64

In [125]:
df = pd.DataFrame({"category": ["a", "a", "a", "a","b", "b", "b", "b"],"data": np.random.standard_normal(8),"weights": np.random.uniform(size=8)})

In [126]:
df

  category      data   weights
0        a  0.856657  0.809335
1        a -3.353139  0.124549
2        a -0.347631  0.195181
3        a -0.554349  0.645418
4        b -1.834881  0.106917
5        b  1.347203  0.327918
6        b -0.011767  0.139627
7        b  0.361642  0.023417

In [127]:
grouped = df.groupby("category")

In [128]:
def get_wavg(group):
  return np.average(group["data"], weights=group["weights"])

In [129]:
grouped.apply(get_wavg)

/tmp/ipython-input-4286695940.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped.apply(get_wavg)

category
a   -0.084501
b    0.422190
dtype: float64

In [131]:
close_px = pd.read_csv("stock_px.csv", parse_dates=True, index_col=0)

In [132]:
close_px.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2214 entries, 2003-01-02 to 2011-10-14
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AAPL    2214 non-null   float64
 1   MSFT    2214 non-null   float64
 2   XOM     2214 non-null   float64
 3   SPX     2214 non-null   float64
dtypes: float64(4)
memory usage: 86.5 KB

In [133]:
close_px.tail(4)

              AAPL   MSFT    XOM      SPX
2011-10-11  400.29  27.00  76.27  1195.54
2011-10-12  402.19  26.96  77.16  1207.25
2011-10-13  408.43  27.18  76.37  1203.66
2011-10-14  422.00  27.27  78.11  1224.58

In [134]:
def spx_corr(group):
  return group.corrwith(group["SPX"])

In [135]:
rets = close_px.pct_change().dropna()

In [138]:
def get_year(x):
  return x.year

In [139]:
by_year = rets.groupby(get_year)

In [140]:
import statsmodels.api as sm

In [141]:
def regress(data, yvar=None, xvars=None):
  Y = data[yvar]
  X = data[xvars]
  X["intercept"] = 1.
  result = sm.OLS(Y, X).fit()
  return result.params

In [142]:
by_year.apply(regress, yvar="AAPL", xvars=["SPX"])

           SPX  intercept
2003  1.195406   0.000710
2004  1.363463   0.004201
2005  1.766415   0.003246
2006  1.645496   0.000080
2007  1.198761   0.003438
2008  0.968016  -0.001110
2009  0.879103   0.002954
2010  1.052608   0.001261
2011  0.806605   0.001514

In [143]:
df = pd.DataFrame({'key': ['a', 'b', 'c'] * 4,'value': np.arange(12.)})

In [144]:
df

   key  value
0    a    0.0
1    b    1.0
2    c    2.0
3    a    3.0
4    b    4.0
5    c    5.0
6    a    6.0
7    b    7.0
8    c    8.0
9    a    9.0
10   b   10.0
11   c   11.0

In [145]:
g = df.groupby("key")["value"]

In [146]:
g.mean()

key
a    4.5
b    5.5
c    6.5
Name: value, dtype: float64

In [156]:
g.groups

{'a': [0, 3, 6, 9], 'b': [1, 4, 7, 10], 'c': [2, 5, 8, 11]}

In [151]:
g.transform('mean')

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [157]:
def times_two(group):
  return group * 2

In [158]:
g.transform(times_two)

0      0.0
1      2.0
2      4.0
3      6.0
4      8.0
5     10.0
6     12.0
7     14.0
8     16.0
9     18.0
10    20.0
11    22.0
Name: value, dtype: float64

In [159]:
def get_ranks(group):
  return group.rank(ascending=False)

In [160]:
g.transform(get_ranks)

0     4.0
1     4.0
2     4.0
3     3.0
4     3.0
5     3.0
6     2.0
7     2.0
8     2.0
9     1.0
10    1.0
11    1.0
Name: value, dtype: float64

In [161]:
def normalize(x):
  return (x - x.mean()) / x.std()

In [162]:
g.transform(normalize)

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [163]:
tips.head()

   total_bill   tip smoker  day    time  size   tip_pct
0       16.99  1.01     No  Sun  Dinner     2  0.059447
1       10.34  1.66     No  Sun  Dinner     3  0.160542
2       21.01  3.50     No  Sun  Dinner     3  0.166587
3       23.68  3.31     No  Sun  Dinner     2  0.139780
4       24.59  3.61     No  Sun  Dinner     4  0.146808

In [166]:
tips.drop("time", axis="columns").pivot_table(index=["day", "smoker"])

                 size       tip   tip_pct  total_bill
day  smoker
Fri  No      2.250000  2.812500  0.151650   18.420000
     Yes     2.066667  2.714000  0.174783   16.813333
Sat  No      2.555556  3.102889  0.158048   19.661778
     Yes     2.476190  2.875476  0.147906   21.276667
Sun  No      2.929825  3.167895  0.160113   20.506667
     Yes     2.578947  3.516842  0.187250   24.120000
Thur No      2.488889  2.673778  0.160298   17.113111
     Yes     2.352941  3.030000  0.163863   19.190588

In [167]:
tips.pivot_table(index=["time", "day"], columns="smoker", values=["tip_pct", "size"])

                 size             tip_pct
smoker             No       Yes        No       Yes
time   day
Dinner Fri   2.000000  2.222222  0.139622  0.165347
       Sat   2.555556  2.476190  0.158048  0.147906
       Sun   2.929825  2.578947  0.160113  0.187250
       Thur  2.000000       NaN  0.159744       NaN
Lunch  Fri   3.000000  1.833333  0.187735  0.188937
       Thur  2.500000  2.352941  0.160311  0.163863

In [168]:
tips.pivot_table(index=["time", "day"], columns="smoker",values=["tip_pct", "size"], margins=True)

                 size                       tip_pct
smoker             No       Yes       All        No       Yes       All
time   day
Dinner Fri   2.000000  2.222222  2.166667  0.139622  0.165347  0.158916
       Sat   2.555556  2.476190  2.517241  0.158048  0.147906  0.153152
       Sun   2.929825  2.578947  2.842105  0.160113  0.187250  0.166897
       Thur  2.000000       NaN  2.000000  0.159744       NaN  0.159744
Lunch  Fri   3.000000  1.833333  2.000000  0.187735  0.188937  0.188765
       Thur  2.500000  2.352941  2.459016  0.160311  0.163863  0.161301
All          2.668874  2.408602  2.569672  0.159328  0.163196  0.160803

In [169]:
tips.pivot_table(index=["time", "smoker"], columns="day", values="tip_pct", aggfunc=len, margins=True)

day             Fri   Sat   Sun  Thur  All
time   smoker
Dinner No       3.0  45.0  57.0   1.0  106
       Yes      9.0  42.0  19.0   NaN   70
Lunch  No       1.0   NaN   NaN  44.0   45
       Yes      6.0   NaN   NaN  17.0   23
All            19.0  87.0  76.0  62.0  244

In [171]:
tips.pivot_table(index=["time", "size", "smoker"], columns="day", values="tip_pct", fill_value=0)

day                      Fri       Sat       Sun      Thur
time   size smoker
Dinner 1    No      0.000000  0.137931  0.000000  0.000000
            Yes     0.000000  0.325733  0.000000  0.000000
       2    No      0.139622  0.162705  0.168859  0.159744
            Yes     0.171297  0.148668  0.207893  0.000000
       3    No      0.000000  0.154661  0.152663  0.000000
            Yes     0.000000  0.144995  0.152660  0.000000
       4    No      0.000000  0.150096  0.148143  0.000000
            Yes     0.117750  0.124515  0.193370  0.000000
       5    No      0.000000  0.000000  0.206928  0.000000
            Yes     0.000000  0.106572  0.065660  0.000000
       6    No      0.000000  0.000000  0.103799  0.000000
Lunch  1    No      0.000000  0.000000  0.000000  0.181728
            Yes     0.223776  0.000000  0.000000  0.000000
       2    No      0.000000  0.000000  0.000000  0.166005
            Yes     0.181969  0.000000  0.000000  0.158843
       3    No      0.187735  0.000000  0.000000  0.084246
            Yes     0.000000  0.000000  0.000000  0.204952
       4    No      0.000000  0.000000  0.000000  0.138919
            Yes     0.000000  0.000000  0.000000  0.155410
       5    No      0.000000  0.000000  0.000000  0.121389
       6    No      0.000000  0.000000  0.000000  0.173706

In [175]:
from io import StringIO

In [176]:
data = """Sample Nationality Handedness
.....: 1 USA Right-handed
.....: 2 Japan Left-handed
.....: 3 USA Right-handed
.....: 4 Japan Right-handed
.....: 5 Japan Left-handed
.....: 6 Japan Right-handed
.....: 7 USA Right-handed
.....: 8 USA Left-handed
.....: 9 Japan Right-handed
.....: 10 USA Right-handed"""

In [177]:
data = pd.read_table(StringIO(data), sep="\s+")

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipython-input-262336665.py:1: SyntaxWarning: invalid escape sequence '\s'
  data = pd.read_table(StringIO(data), sep="\s+")

In [178]:
data

   Sample Nationality    Handedness
0       1         USA  Right-handed
1       2       Japan   Left-handed
2       3         USA  Right-handed
3       4       Japan  Right-handed
4       5       Japan   Left-handed
5       6       Japan  Right-handed
6       7         USA  Right-handed
7       8         USA   Left-handed
8       9       Japan  Right-handed
9      10         USA  Right-handed

In [180]:
pd.crosstab(data["Nationality"], data["Handedness"], margins=True)

Handedness   Left-handed  Right-handed  All
Nationality
Japan                  2             3    5
USA                    1             4    5
All                    3             7   10

In [181]:
pd.crosstab([tips["time"], tips["day"]], tips["smoker"], margins=True)

smoker        No  Yes  All
time   day
Dinner Fri     3    9   12
       Sat    45   42   87
       Sun    57   19   76
       Thur    1    0    1
Lunch  Fri     1    6    7
       Thur   44   17   61
All          151   93  244