In [3]:
import numpy as np
import pandas as pd

In [4]:
data = pd.DataFrame({'x0': [1, 2, 3, 4, 5],'x1': [0.01, -0.01, 0.25, -4.1, 0.],'y': [-1.5, 0., 3.6, 1.3, -2.]})

In [5]:
data

   x0    x1    y
0   1  0.01 -1.5
1   2 -0.01  0.0
2   3  0.25  3.6
3   4 -4.10  1.3
4   5  0.00 -2.0

In [6]:
data.columns

Index(['x0', 'x1', 'y'], dtype='object')

In [7]:
data.to_numpy()

array([[ 1.  ,  0.01, -1.5 ],
       [ 2.  , -0.01,  0.  ],
       [ 3.  ,  0.25,  3.6 ],
       [ 4.  , -4.1 ,  1.3 ],
       [ 5.  ,  0.  , -2.  ]])

In [8]:
df2 = pd.DataFrame(data.to_numpy(), columns=['one', 'two', 'three'])

In [9]:
df2

   one   two  three
0  1.0  0.01   -1.5
1  2.0 -0.01    0.0
2  3.0  0.25    3.6
3  4.0 -4.10    1.3
4  5.0  0.00   -2.0

In [10]:
df3 = data.copy()

In [11]:
df3["string"] = ["a", "b", "c", "d", "e"]

In [12]:
df3

   x0    x1    y string
0   1  0.01 -1.5      a
1   2 -0.01  0.0      b
2   3  0.25  3.6      c
3   4 -4.10  1.3      d
4   5  0.00 -2.0      e

In [13]:
df3.to_numpy()

array([[1, 0.01, -1.5, 'a'],
       [2, -0.01, 0.0, 'b'],
       [3, 0.25, 3.6, 'c'],
       [4, -4.1, 1.3, 'd'],
       [5, 0.0, -2.0, 'e']], dtype=object)

In [14]:
model_cols = ["x0", "x1"]

In [15]:
data.loc[:, model_cols].to_numpy()

array([[ 1.  ,  0.01],
       [ 2.  , -0.01],
       [ 3.  ,  0.25],
       [ 4.  , -4.1 ],
       [ 5.  ,  0.  ]])

In [16]:
data['category'] = pd.Categorical(['a', 'b', 'a', 'a', 'b'],categories=['a', 'b'])

In [17]:
data

   x0    x1    y category
0   1  0.01 -1.5        a
1   2 -0.01  0.0        b
2   3  0.25  3.6        a
3   4 -4.10  1.3        a
4   5  0.00 -2.0        b

In [18]:
dummies = pd.get_dummies(data.category, prefix="category")

In [19]:
data_with_dummies = data.drop("category", axis="columns").join(dummies)

In [20]:
data_with_dummies

   x0    x1    y  category_a  category_b
0   1  0.01 -1.5        True       False
1   2 -0.01  0.0       False        True
2   3  0.25  3.6        True       False
3   4 -4.10  1.3        True       False
4   5  0.00 -2.0       False        True

In [21]:
data = pd.DataFrame({'x0': [1, 2, 3, 4, 5],'x1': [0.01, -0.01, 0.25, -4.1, 0.],'y': [-1.5, 0., 3.6, 1.3, -2.]})

In [22]:
data

   x0    x1    y
0   1  0.01 -1.5
1   2 -0.01  0.0
2   3  0.25  3.6
3   4 -4.10  1.3
4   5  0.00 -2.0

In [23]:
import patsy

In [24]:
y, X = patsy.dmatrices('y ~ x0 + x1', data)

In [25]:
y

DesignMatrix with shape (5, 1)
     y
  -1.5
   0.0
   3.6
   1.3
  -2.0
  Terms:
    'y' (column 0)

In [26]:
X

DesignMatrix with shape (5, 3)
  Intercept  x0     x1
          1   1   0.01
          1   2  -0.01
          1   3   0.25
          1   4  -4.10
          1   5   0.00
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'x1' (column 2)

In [27]:
np.asarray(y)

array([[-1.5],
       [ 0. ],
       [ 3.6],
       [ 1.3],
       [-2. ]])

In [28]:
np.asarray(X)

array([[ 1.  ,  1.  ,  0.01],
       [ 1.  ,  2.  , -0.01],
       [ 1.  ,  3.  ,  0.25],
       [ 1.  ,  4.  , -4.1 ],
       [ 1.  ,  5.  ,  0.  ]])

In [29]:
patsy.dmatrices("y ~ x0 + x1 + 0", data)[1]

DesignMatrix with shape (5, 2)
  x0     x1
   1   0.01
   2  -0.01
   3   0.25
   4  -4.10
   5   0.00
  Terms:
    'x0' (column 0)
    'x1' (column 1)

In [30]:
coef, resid, _, _ = np.linalg.lstsq(X, y)

In [31]:
coef

array([[ 0.31290976],
       [-0.07910564],
       [-0.26546384]])

In [32]:
coef = pd.Series(coef.squeeze(), index=X.design_info.column_names)

In [33]:
coef

Intercept    0.312910
x0          -0.079106
x1          -0.265464
dtype: float64

In [34]:
y, X = patsy.dmatrices("y ~ x0 + np.log(np.abs(x1) + 1)", data)

In [35]:
X

DesignMatrix with shape (5, 3)
  Intercept  x0  np.log(np.abs(x1) + 1)
          1   1                 0.00995
          1   2                 0.00995
          1   3                 0.22314
          1   4                 1.62924
          1   5                 0.00000
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'np.log(np.abs(x1) + 1)' (column 2)

In [36]:
y, X = patsy.dmatrices("y ~ standardize(x0) + center(x1)", data)

In [37]:
X

DesignMatrix with shape (5, 3)
  Intercept  standardize(x0)  center(x1)
          1         -1.41421        0.78
          1         -0.70711        0.76
          1          0.00000        1.02
          1          0.70711       -3.33
          1          1.41421        0.77
  Terms:
    'Intercept' (column 0)
    'standardize(x0)' (column 1)
    'center(x1)' (column 2)

In [38]:
new_data = pd.DataFrame({'x0': [6, 7, 8, 9],'x1': [3.1, -0.5, 0, 2.3],'y': [1, 2, 3, 4]})

In [39]:
new_X = patsy.build_design_matrices([X.design_info], new_data)

In [40]:
new_X

[DesignMatrix with shape (4, 3)
   Intercept  standardize(x0)  center(x1)
           1          2.12132        3.87
           1          2.82843        0.27
           1          3.53553        0.77
           1          4.24264        3.07
   Terms:
     'Intercept' (column 0)
     'standardize(x0)' (column 1)
     'center(x1)' (column 2)]

In [41]:
y, X = patsy.dmatrices("y ~ I(x0 + x1)", data)

In [42]:
data = pd.DataFrame({'key1': ['a', 'a', 'b', 'b', 'a', 'b', 'a', 'b'],'key2': [0, 1, 0, 1, 0, 1, 0, 0],'v1': [1, 2, 3, 4, 5, 6, 7, 8],'v2': [-1, 0, 2.5, -0.5, 4.0, -1.2, 0.2, -1.7]})

In [43]:
y, X = patsy.dmatrices("v2 ~ key1", data)

In [44]:
X

DesignMatrix with shape (8, 2)
  Intercept  key1[T.b]
          1          0
          1          0
          1          1
          1          1
          1          0
          1          1
          1          0
          1          1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)

In [45]:
data

  key1  key2  v1   v2
0    a     0   1 -1.0
1    a     1   2  0.0
2    b     0   3  2.5
3    b     1   4 -0.5
4    a     0   5  4.0
5    b     1   6 -1.2
6    a     0   7  0.2
7    b     0   8 -1.7

In [46]:
data["key2"] = data["key2"].map({0: "zero", 1: "one"})

In [47]:
data

  key1  key2  v1   v2
0    a  zero   1 -1.0
1    a   one   2  0.0
2    b  zero   3  2.5
3    b   one   4 -0.5
4    a  zero   5  4.0
5    b   one   6 -1.2
6    a  zero   7  0.2
7    b  zero   8 -1.7

In [48]:
y, X = patsy.dmatrices("v2 ~ key1 + key2", data)

In [49]:
X

DesignMatrix with shape (8, 3)
  Intercept  key1[T.b]  key2[T.zero]
          1          0             1
          1          0             0
          1          1             1
          1          1             0
          1          0             1
          1          1             0
          1          0             1
          1          1             1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)
    'key2' (column 2)

In [50]:
y, X = patsy.dmatrices("v2 ~ key1 + key2 + key1:key2", data)

In [51]:
X

DesignMatrix with shape (8, 4)
  Intercept  key1[T.b]  key2[T.zero]  key1[T.b]:key2[T.zero]
          1          0             1                       0
          1          0             0                       0
          1          1             1                       1
          1          1             0                       0
          1          0             1                       0
          1          1             0                       0
          1          0             1                       0
          1          1             1                       1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)
    'key2' (column 2)
    'key1:key2' (column 3)

In [56]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [53]:
# To make the example reproducible
rng = np.random.default_rng(seed=12345)

def dnorm(mean, variance, size=1):
  if isinstance(size, int):
    size = size,
  return mean + np.sqrt(variance) * rng.standard_normal(*size)

N = 100
X = np.c_[dnorm(0, 0.4, size=N),
dnorm(0, 0.6, size=N),
dnorm(0, 0.2, size=N)]
eps = dnorm(0, 0.1, size=N)
beta = [0.1, 0.3, 0.5]
y = np.dot(X, beta) + eps

In [54]:
X[:5]

array([[-0.90050602, -0.18942958, -1.0278702 ],
       [ 0.79925205, -1.54598388, -0.32739708],
       [-0.55065483, -0.12025429,  0.32935899],
       [-0.16391555,  0.82403985,  0.20827485],
       [-0.04765129, -0.21314698, -0.04824364]])

In [55]:
y[:5]

array([-0.59952668, -0.58845445,  0.18563386, -0.00747657, -0.01537445])

In [57]:
X_model = sm.add_constant(X)

In [58]:
X_model[:5]

array([[ 1.        , -0.90050602, -0.18942958, -1.0278702 ],
       [ 1.        ,  0.79925205, -1.54598388, -0.32739708],
       [ 1.        , -0.55065483, -0.12025429,  0.32935899],
       [ 1.        , -0.16391555,  0.82403985,  0.20827485],
       [ 1.        , -0.04765129, -0.21314698, -0.04824364]])

In [59]:
type(X_model)

numpy.ndarray

In [60]:
model = sm.OLS(y, X)

In [61]:
results = model.fit()

In [62]:
results.params

array([0.06681503, 0.26803235, 0.45052319])

In [64]:
print(results.summary())

                                 OLS Regression Results
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.469
Model:                            OLS   Adj. R-squared (uncentered):              0.452
Method:                 Least Squares   F-statistic:                              28.51
Date:                Tue, 02 Sep 2025   Prob (F-statistic):                    2.66e-13
Time:                        13:51:37   Log-Likelihood:                         -25.611
No. Observations:                 100   AIC:                                      57.22
Df Residuals:                      97   BIC:                                      65.04
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.0668      0.054      1.243      0.217      -0.040       0.174
x2             0.2680      0.042      6.313      0.000       0.184       0.352
x3             0.4505      0.068      6.605      0.000       0.315       0.586
==============================================================================
Omnibus:                        0.435   Durbin-Watson:                   1.869
Prob(Omnibus):                  0.805   Jarque-Bera (JB):                0.301
Skew:                           0.134   Prob(JB):                        0.860
Kurtosis:                       2.995   Cond. No.                         1.64
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [65]:
data = pd.DataFrame(X, columns=["col0", "col1", "col2"])

In [66]:
data["y"] = y

In [67]:
data[:5]

       col0      col1      col2         y
0 -0.900506 -0.189430 -1.027870 -0.599527
1  0.799252 -1.545984 -0.327397 -0.588454
2 -0.550655 -0.120254  0.329359  0.185634
3 -0.163916  0.824040  0.208275 -0.007477
4 -0.047651 -0.213147 -0.048244 -0.015374

In [68]:
results = smf.ols("y ~ col0 + col1 + col2", data=data).fit()

In [69]:
results.params

Intercept   -0.020799
col0         0.065813
col1         0.268970
col2         0.449419
dtype: float64

In [71]:
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.470
Model:                            OLS   Adj. R-squared:                  0.453
Method:                 Least Squares   F-statistic:                     28.36
Date:                Tue, 02 Sep 2025   Prob (F-statistic):           3.23e-13
Time:                        13:57:00   Log-Likelihood:                -25.390
No. Observations:                 100   AIC:                             58.78
Df Residuals:                      96   BIC:                             69.20
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -0.0208      0.032     -0.653      0.516      -0.084       0.042
col0           0.0658      0.054      1.220      0.226      -0.041       0.173
col1           0.2690      0.043      6.312      0.000       0.184       0.354
col2           0.4494      0.068      6.567      0.000       0.314       0.585
==============================================================================
Omnibus:                        0.429   Durbin-Watson:                   1.878
Prob(Omnibus):                  0.807   Jarque-Bera (JB):                0.296
Skew:                           0.133   Prob(JB):                        0.863
Kurtosis:                       2.995   Cond. No.                         2.16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [73]:
type(results.summary())

statsmodels.iolib.summary.Summary

In [76]:
results.tvalues

Intercept   -0.652501
col0         1.219768
col1         6.312369
col2         6.567428
dtype: float64

In [77]:
results.predict(data[:5])

0   -0.592959
1   -0.531160
2    0.058636
3    0.283658
4   -0.102947
dtype: float64

In [78]:
init_x = 4
values = [init_x, init_x]
N = 1000
b0 = 0.8
b1 = -0.4
noise = dnorm(0, 0.1, N)
for i in range(N):
  new_x = values[-1] * b0 + values[-2] * b1 + noise[i]
  values.append(new_x)

In [79]:
train = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Data/examples_of_pydata_book/datasets/titanic/train.csv')

In [80]:
test = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Data/examples_of_pydata_book/datasets/titanic/test.csv')

In [82]:
train.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [87]:
# no matter true, false or nan, every existed value(including nan values) will be counted in method count
# so we have to use sum() here
train.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [88]:
test.isna().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [89]:
impute_value = train["Age"].median()

In [90]:
train["Age"] = train["Age"].fillna(impute_value)

In [91]:
test["Age"] = test["Age"].fillna(impute_value)

In [92]:
train["IsFemale"] = (train["Sex"] == "female").astype(int)

In [93]:
test["IsFemale"] = (test["Sex"] == "female").astype(int)

In [94]:
predictors = ["Pclass", "IsFemale", "Age"]

In [95]:
X_train = train[predictors].to_numpy()

In [96]:
X_test = test[predictors].to_numpy()

In [97]:
y_train = train["Survived"].to_numpy()

In [98]:
X_train[:5]

array([[ 3.,  0., 22.],
       [ 1.,  1., 38.],
       [ 3.,  1., 26.],
       [ 1.,  1., 35.],
       [ 3.,  0., 35.]])

In [99]:
y_train[:5]

array([0, 1, 1, 1, 0])

In [100]:
from sklearn.linear_model import LogisticRegression

In [101]:
model = LogisticRegression()

In [102]:
model.fit(X_train, y_train)

LogisticRegression()

In [103]:
y_predict = model.predict(X_test)

In [104]:
y_predict[:10]

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0])

In [106]:
from sklearn.linear_model import LogisticRegressionCV

In [107]:
model_cv = LogisticRegressionCV(Cs=10)

In [109]:
model_cv.fit(X_train, y_train)

LogisticRegressionCV()

In [111]:
from sklearn.model_selection import cross_val_score

In [113]:
model = LogisticRegression(C=10)

In [114]:
scores = cross_val_score(model, X_train, y_train, cv=4)

In [115]:
scores

array([0.77578475, 0.79820628, 0.77578475, 0.78828829])