In [1]:
import pandas as pd
import numpy as np

In [2]:
from datetime import datetime

In [3]:
now = datetime.now()

In [4]:
now

datetime.datetime(2025, 9, 17, 15, 13, 46, 986225)

In [5]:
now.year, now.month, now.day

(2025, 9, 17)

In [6]:
delta = datetime(2011, 1, 7) - datetime(2008, 6, 24, 8, 15)

In [7]:
delta

datetime.timedelta(days=926, seconds=56700)

In [8]:
delta.days

926

In [9]:
delta.seconds

56700

In [10]:
from datetime import timedelta

In [11]:
start = datetime(2011, 11, 7)

In [12]:
start + timedelta(12)

datetime.datetime(2011, 11, 19, 0, 0)

In [13]:
start - 2 * timedelta(12)

datetime.datetime(2011, 10, 14, 0, 0)

In [14]:
stamp = datetime(2011, 1, 3)

In [15]:
str(stamp)

'2011-01-03 00:00:00'

In [16]:
stamp.strftime("%Y-%m-%d")

'2011-01-03'

In [17]:
value = "2011-01-03"

In [18]:
datetime.strptime(value, "%Y-%m-%d")

datetime.datetime(2011, 1, 3, 0, 0)

In [19]:
datestrs = ["7/6/2011", "8/6/2011"]

In [20]:
[datetime.strptime(x, "%m/%d/%Y") for x in datestrs]

[datetime.datetime(2011, 7, 6, 0, 0), datetime.datetime(2011, 8, 6, 0, 0)]

In [21]:
datestrs = ["2011-07-06 12:00:00", "2011-08-06 00:00:00"]

In [22]:
pd.to_datetime(datestrs)

DatetimeIndex(['2011-07-06 12:00:00', '2011-08-06 00:00:00'], dtype='datetime64[ns]', freq=None)

In [23]:
idx = pd.to_datetime(datestrs + [None])

In [24]:
idx

DatetimeIndex(['2011-07-06 12:00:00', '2011-08-06 00:00:00', 'NaT'], dtype='datetime64[ns]', freq=None)

In [25]:
idx[2]

NaT

In [26]:
pd.isna(idx)

array([False, False,  True])

In [27]:
dates = [datetime(2011, 1, 2), datetime(2011, 1, 5),datetime(2011, 1, 7), datetime(2011, 1, 8),datetime(2011, 1, 10), datetime(2011, 1, 12)]

In [28]:
ts = pd.Series(np.random.standard_normal(6), index=dates)

In [29]:
ts

2011-01-02   -0.717757
2011-01-05    0.708002
2011-01-07    2.344032
2011-01-08    0.885471
2011-01-10    0.854670
2011-01-12   -0.991502
dtype: float64

In [30]:
ts.index

DatetimeIndex(['2011-01-02', '2011-01-05', '2011-01-07', '2011-01-08',
               '2011-01-10', '2011-01-12'],
              dtype='datetime64[ns]', freq=None)

In [31]:
ts[::2]

2011-01-02   -0.717757
2011-01-07    2.344032
2011-01-10    0.854670
dtype: float64

In [32]:
ts + ts[::2]

2011-01-02   -1.435513
2011-01-05         NaN
2011-01-07    4.688064
2011-01-08         NaN
2011-01-10    1.709341
2011-01-12         NaN
dtype: float64

In [33]:
ts.index.dtype

dtype('<M8[ns]')

In [34]:
stamp = ts.index[0]

In [35]:
stamp

Timestamp('2011-01-02 00:00:00')

In [36]:
stamp = ts.index[2]

In [37]:
ts[stamp]

np.float64(2.344031772483856)

In [38]:
ts["2011-01-10"]

np.float64(0.8546703145935093)

In [39]:
longer_ts = pd.Series(np.random.standard_normal(1000), index=pd.date_range("2000-01-01", periods=1000))

In [40]:
longer_ts

2000-01-01   -0.890306
2000-01-02    1.148019
2000-01-03   -2.053609
2000-01-04    1.662900
2000-01-05   -1.314053
                ...
2002-09-22   -0.682944
2002-09-23    0.330402
2002-09-24   -0.436127
2002-09-25    0.307788
2002-09-26   -1.335427
Freq: D, Length: 1000, dtype: float64

In [41]:
longer_ts["2001"]

2001-01-01    0.057422
2001-01-02   -0.860939
2001-01-03   -0.447610
2001-01-04   -1.150243
2001-01-05   -1.450747
                ...
2001-12-27    0.256133
2001-12-28   -0.072416
2001-12-29    0.947291
2001-12-30    0.225168
2001-12-31    1.299545
Freq: D, Length: 365, dtype: float64

In [42]:
longer_ts["2001-05"]

2001-05-01    1.026096
2001-05-02   -0.252700
2001-05-03    1.080696
2001-05-04   -2.539507
2001-05-05   -1.416130
2001-05-06   -0.764961
2001-05-07    1.881905
2001-05-08   -1.611057
2001-05-09   -0.661123
2001-05-10   -0.195185
2001-05-11   -1.114653
2001-05-12   -1.887403
2001-05-13   -1.448336
2001-05-14    0.038531
2001-05-15   -1.340740
2001-05-16    1.284829
2001-05-17   -2.839471
2001-05-18    0.829576
2001-05-19    0.232492
2001-05-20    1.010279
2001-05-21    0.154329
2001-05-22    0.934521
2001-05-23   -0.393211
2001-05-24   -0.902812
2001-05-25    0.102977
2001-05-26   -0.795354
2001-05-27    0.766787
2001-05-28    0.844409
2001-05-29   -0.352119
2001-05-30   -1.046341
2001-05-31    0.176905
Freq: D, dtype: float64

In [43]:
ts[datetime(2011, 1, 7)]

np.float64(2.344031772483856)

In [44]:
ts[datetime(2011, 1, 7):datetime(2011, 1, 10)]

2011-01-07    2.344032
2011-01-08    0.885471
2011-01-10    0.854670
dtype: float64

In [45]:
ts

2011-01-02   -0.717757
2011-01-05    0.708002
2011-01-07    2.344032
2011-01-08    0.885471
2011-01-10    0.854670
2011-01-12   -0.991502
dtype: float64

In [46]:
ts["2011-01-06":"2011-01-11"]

2011-01-07    2.344032
2011-01-08    0.885471
2011-01-10    0.854670
dtype: float64

In [47]:
ts.truncate(after="2011-01-09")

2011-01-02   -0.717757
2011-01-05    0.708002
2011-01-07    2.344032
2011-01-08    0.885471
dtype: float64

In [48]:
dates = pd.date_range("2000-01-01", periods=100, freq="W-WED")

In [49]:
long_df = pd.DataFrame(np.random.standard_normal((100, 4)),
                       index=dates,
                       columns=["Colorado", "Texas",
                                "New York", "Ohio"])

In [50]:
long_df.loc["2001-05"]

            Colorado     Texas  New York      Ohio
2001-05-02  0.719408 -0.352558 -0.072801 -0.278478
2001-05-09  1.756374  0.741042  0.299378 -1.914150
2001-05-16  1.452576  0.769064  0.044815  0.587786
2001-05-23 -1.033166 -0.968150 -0.143182 -1.701186
2001-05-30  0.787354 -0.461580 -1.635948  2.307681

In [51]:
dates = pd.DatetimeIndex(["2000-01-01", "2000-01-02", "2000-01-02", "2000-01-02", "2000-01-03"])

In [52]:
dup_ts = pd.Series(np.arange(5), index=dates)

In [53]:
dup_ts

2000-01-01    0
2000-01-02    1
2000-01-02    2
2000-01-02    3
2000-01-03    4
dtype: int64

In [54]:
dup_ts.index.is_unique

False

In [55]:
dup_ts["2000-01-03"]

np.int64(4)

In [56]:
dup_ts["2000-01-02"]

2000-01-02    1
2000-01-02    2
2000-01-02    3
dtype: int64

In [57]:
grouped = dup_ts.groupby(level=0)

In [58]:
grouped.mean()

2000-01-01    0.0
2000-01-02    2.0
2000-01-03    4.0
dtype: float64

In [59]:
grouped.groups

{2000-01-01 00:00:00: [2000-01-01 00:00:00], 2000-01-02 00:00:00: [2000-01-02 00:00:00, 2000-01-02 00:00:00, 2000-01-02 00:00:00], 2000-01-03 00:00:00: [2000-01-03 00:00:00]}

In [60]:
grouped.count()

2000-01-01    1
2000-01-02    3
2000-01-03    1
dtype: int64

In [61]:
ts

2011-01-02   -0.717757
2011-01-05    0.708002
2011-01-07    2.344032
2011-01-08    0.885471
2011-01-10    0.854670
2011-01-12   -0.991502
dtype: float64

In [62]:
resampler = ts.resample("D")

In [63]:
resampler

In [64]:
index = pd.date_range("2012-04-01", "2012-06-01")

In [65]:
index

DatetimeIndex(['2012-04-01', '2012-04-02', '2012-04-03', '2012-04-04',
               '2012-04-05', '2012-04-06', '2012-04-07', '2012-04-08',
               '2012-04-09', '2012-04-10', '2012-04-11', '2012-04-12',
               '2012-04-13', '2012-04-14', '2012-04-15', '2012-04-16',
               '2012-04-17', '2012-04-18', '2012-04-19', '2012-04-20',
               '2012-04-21', '2012-04-22', '2012-04-23', '2012-04-24',
               '2012-04-25', '2012-04-26', '2012-04-27', '2012-04-28',
               '2012-04-29', '2012-04-30', '2012-05-01', '2012-05-02',
               '2012-05-03', '2012-05-04', '2012-05-05', '2012-05-06',
               '2012-05-07', '2012-05-08', '2012-05-09', '2012-05-10',
               '2012-05-11', '2012-05-12', '2012-05-13', '2012-05-14',
               '2012-05-15', '2012-05-16', '2012-05-17', '2012-05-18',
               '2012-05-19', '2012-05-20', '2012-05-21', '2012-05-22',
               '2012-05-23', '2012-05-24', '2012-05-25', '2012-05-26',
               '2012-05-27', '2012-05-28', '2012-05-29', '2012-05-30',
               '2012-05-31', '2012-06-01'],
              dtype='datetime64[ns]', freq='D')

In [66]:
pd.date_range(start="2012-04-01", periods=20)

DatetimeIndex(['2012-04-01', '2012-04-02', '2012-04-03', '2012-04-04',
               '2012-04-05', '2012-04-06', '2012-04-07', '2012-04-08',
               '2012-04-09', '2012-04-10', '2012-04-11', '2012-04-12',
               '2012-04-13', '2012-04-14', '2012-04-15', '2012-04-16',
               '2012-04-17', '2012-04-18', '2012-04-19', '2012-04-20'],
              dtype='datetime64[ns]', freq='D')

In [67]:
pd.date_range(end="2012-06-01", periods=20)

DatetimeIndex(['2012-05-13', '2012-05-14', '2012-05-15', '2012-05-16',
               '2012-05-17', '2012-05-18', '2012-05-19', '2012-05-20',
               '2012-05-21', '2012-05-22', '2012-05-23', '2012-05-24',
               '2012-05-25', '2012-05-26', '2012-05-27', '2012-05-28',
               '2012-05-29', '2012-05-30', '2012-05-31', '2012-06-01'],
              dtype='datetime64[ns]', freq='D')

In [68]:
pd.date_range("2000-01-01", "2000-12-01", freq="BM")

/tmp/ipython-input-3742551278.py:1: FutureWarning: 'BM' is deprecated and will be removed in a future version, please use 'BME' instead.
  pd.date_range("2000-01-01", "2000-12-01", freq="BM")

DatetimeIndex(['2000-01-31', '2000-02-29', '2000-03-31', '2000-04-28',
               '2000-05-31', '2000-06-30', '2000-07-31', '2000-08-31',
               '2000-09-29', '2000-10-31', '2000-11-30'],
              dtype='datetime64[ns]', freq='BME')

In [69]:
pd.date_range("2012-05-02 12:56:31", periods=5, normalize=True)

DatetimeIndex(['2012-05-02', '2012-05-03', '2012-05-04', '2012-05-05',
               '2012-05-06'],
              dtype='datetime64[ns]', freq='D')

In [70]:
from pandas.tseries.offsets import Hour, Minute

In [71]:
hour = Hour()

In [72]:
hour

In [73]:
four_hours = Hour(4)

In [74]:
Hour(2) + Minute(30)

In [75]:
pd.date_range("2000-01-01", periods=10, freq="1h30min")

DatetimeIndex(['2000-01-01 00:00:00', '2000-01-01 01:30:00',
               '2000-01-01 03:00:00', '2000-01-01 04:30:00',
               '2000-01-01 06:00:00', '2000-01-01 07:30:00',
               '2000-01-01 09:00:00', '2000-01-01 10:30:00',
               '2000-01-01 12:00:00', '2000-01-01 13:30:00'],
              dtype='datetime64[ns]', freq='90min')

In [76]:
monthly_dates = pd.date_range("2012-01-01", "2012-09-01", freq="WOM-3FRI")

In [77]:
list(monthly_dates)

[Timestamp('2012-01-20 00:00:00'),
 Timestamp('2012-02-17 00:00:00'),
 Timestamp('2012-03-16 00:00:00'),
 Timestamp('2012-04-20 00:00:00'),
 Timestamp('2012-05-18 00:00:00'),
 Timestamp('2012-06-15 00:00:00'),
 Timestamp('2012-07-20 00:00:00'),
 Timestamp('2012-08-17 00:00:00')]

In [78]:
ts = pd.Series(np.random.standard_normal(4), index=pd.date_range("2000-01-01", periods=4, freq="M"))

/tmp/ipython-input-273291729.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  ts = pd.Series(np.random.standard_normal(4), index=pd.date_range("2000-01-01", periods=4, freq="M"))

In [79]:
ts

2000-01-31    0.340010
2000-02-29    1.454918
2000-03-31   -0.366393
2000-04-30   -0.802023
Freq: ME, dtype: float64

In [80]:
ts.shift(2)

2000-01-31         NaN
2000-02-29         NaN
2000-03-31    0.340010
2000-04-30    1.454918
Freq: ME, dtype: float64

In [81]:
ts.shift(-2)

2000-01-31   -0.366393
2000-02-29   -0.802023
2000-03-31         NaN
2000-04-30         NaN
Freq: ME, dtype: float64

In [82]:
ts.shift(2, freq="M")

/tmp/ipython-input-903147437.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  ts.shift(2, freq="M")

2000-03-31    0.340010
2000-04-30    1.454918
2000-05-31   -0.366393
2000-06-30   -0.802023
Freq: ME, dtype: float64

In [83]:
ts.shift(3, freq="D")

2000-02-03    0.340010
2000-03-03    1.454918
2000-04-03   -0.366393
2000-05-03   -0.802023
dtype: float64

In [84]:
ts.shift(90, freq="90T")

/tmp/ipython-input-1617709123.py:1: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  ts.shift(90, freq="90T")

2000-02-05 15:00:00    0.340010
2000-03-05 15:00:00    1.454918
2000-04-05 15:00:00   -0.366393
2000-05-05 15:00:00   -0.802023
dtype: float64

In [85]:
from pandas.tseries.offsets import Day, MonthEnd

In [86]:
now = datetime(2011, 11, 17)

In [87]:
now + 3 * Day()

Timestamp('2011-11-20 00:00:00')

In [88]:
now + MonthEnd()

Timestamp('2011-11-30 00:00:00')

In [89]:
now + MonthEnd(2)

Timestamp('2011-12-31 00:00:00')

In [90]:
offset = MonthEnd()

In [91]:
offset.rollforward(now)

Timestamp('2011-11-30 00:00:00')

In [92]:
offset.rollback(now)

Timestamp('2011-10-31 00:00:00')

In [93]:
ts = pd.Series(np.random.standard_normal(20), index=pd.date_range("2000-01-15", periods=20, freq="4D"))

In [94]:
ts

2000-01-15   -2.195782
2000-01-19   -0.250495
2000-01-23   -1.487384
2000-01-27   -0.073889
2000-01-31    0.409854
2000-02-04   -1.326677
2000-02-08    0.505720
2000-02-12   -0.011731
2000-02-16    0.799230
2000-02-20   -1.216358
2000-02-24    0.125697
2000-02-28    0.218369
2000-03-03    1.040749
2000-03-07    1.454749
2000-03-11   -0.286200
2000-03-15    1.783171
2000-03-19   -0.560118
2000-03-23    0.975910
2000-03-27    0.276693
2000-03-31    0.587740
Freq: 4D, dtype: float64

In [95]:
ts.groupby(MonthEnd().rollforward).mean()

2000-01-31   -0.719539
2000-02-29   -0.129393
2000-03-31    0.659087
dtype: float64

In [96]:
ts.resample("M").mean()

/tmp/ipython-input-3978117481.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  ts.resample("M").mean()

2000-01-31   -0.719539
2000-02-29   -0.129393
2000-03-31    0.659087
Freq: ME, dtype: float64

In [97]:
import pytz

In [98]:
pytz.common_timezones[-5:]

['US/Eastern', 'US/Hawaii', 'US/Mountain', 'US/Pacific', 'UTC']

In [99]:
tz = pytz.timezone("America/New_York")

In [100]:
tz

In [101]:
dates = pd.date_range("2012-03-09", periods=6)

In [102]:
ts=pd.Series(np.random.standard_normal(len(dates)), index=dates)

In [103]:
ts

2012-03-09    0.009976
2012-03-10   -0.230907
2012-03-11    1.043245
2012-03-12    2.328820
2012-03-13   -1.644311
2012-03-14   -0.380315
Freq: D, dtype: float64

In [104]:
print(ts.index.tz)

None

In [106]:
pd.date_range("2012-03-09 09:30", periods=10, tz="UTC")

DatetimeIndex(['2012-03-09 09:30:00+00:00', '2012-03-10 09:30:00+00:00',
               '2012-03-11 09:30:00+00:00', '2012-03-12 09:30:00+00:00',
               '2012-03-13 09:30:00+00:00', '2012-03-14 09:30:00+00:00',
               '2012-03-15 09:30:00+00:00', '2012-03-16 09:30:00+00:00',
               '2012-03-17 09:30:00+00:00', '2012-03-18 09:30:00+00:00'],
              dtype='datetime64[ns, UTC]', freq='D')

In [107]:
ts

2012-03-09    0.009976
2012-03-10   -0.230907
2012-03-11    1.043245
2012-03-12    2.328820
2012-03-13   -1.644311
2012-03-14   -0.380315
Freq: D, dtype: float64

In [108]:
ts_utc = ts.tz_localize("UTC")

In [109]:
ts_utc

2012-03-09 00:00:00+00:00    0.009976
2012-03-10 00:00:00+00:00   -0.230907
2012-03-11 00:00:00+00:00    1.043245
2012-03-12 00:00:00+00:00    2.328820
2012-03-13 00:00:00+00:00   -1.644311
2012-03-14 00:00:00+00:00   -0.380315
Freq: D, dtype: float64

In [110]:
ts_utc.index

DatetimeIndex(['2012-03-09 00:00:00+00:00', '2012-03-10 00:00:00+00:00',
               '2012-03-11 00:00:00+00:00', '2012-03-12 00:00:00+00:00',
               '2012-03-13 00:00:00+00:00', '2012-03-14 00:00:00+00:00'],
              dtype='datetime64[ns, UTC]', freq='D')

In [111]:
ts_utc.tz_convert("America/New_York")

2012-03-08 19:00:00-05:00    0.009976
2012-03-09 19:00:00-05:00   -0.230907
2012-03-10 19:00:00-05:00    1.043245
2012-03-11 20:00:00-04:00    2.328820
2012-03-12 20:00:00-04:00   -1.644311
2012-03-13 20:00:00-04:00   -0.380315
Freq: D, dtype: float64

In [112]:
ts_eastern = ts.tz_localize("America/New_York")

In [113]:
ts_eastern.tz_convert("UTC")

2012-03-09 05:00:00+00:00    0.009976
2012-03-10 05:00:00+00:00   -0.230907
2012-03-11 05:00:00+00:00    1.043245
2012-03-12 04:00:00+00:00    2.328820
2012-03-13 04:00:00+00:00   -1.644311
2012-03-14 04:00:00+00:00   -0.380315
dtype: float64

In [114]:
ts_eastern.tz_convert("Europe/Berlin")

2012-03-09 06:00:00+01:00    0.009976
2012-03-10 06:00:00+01:00   -0.230907
2012-03-11 06:00:00+01:00    1.043245
2012-03-12 05:00:00+01:00    2.328820
2012-03-13 05:00:00+01:00   -1.644311
2012-03-14 05:00:00+01:00   -0.380315
dtype: float64

In [115]:
ts.tz_localize("Asia/Shanghai")

2012-03-09 00:00:00+08:00    0.009976
2012-03-10 00:00:00+08:00   -0.230907
2012-03-11 00:00:00+08:00    1.043245
2012-03-12 00:00:00+08:00    2.328820
2012-03-13 00:00:00+08:00   -1.644311
2012-03-14 00:00:00+08:00   -0.380315
dtype: float64

In [116]:
stamp = pd.Timestamp("2011-03-12 04:00")

In [117]:
stamp_utc = stamp.tz_localize("UTC")

In [118]:
stamp_utc.tz_convert("America/New_York")

Timestamp('2011-03-11 23:00:00-0500', tz='America/New_York')

In [119]:
stamp_moscow = pd.Timestamp("2011-03-12 04:00", tz="Europe/Moscow")

In [120]:
stamp_moscow

Timestamp('2011-03-12 04:00:00+0300', tz='Europe/Moscow')

In [121]:
stamp = pd.Timestamp("2012-03-11 01:30", tz="US/Eastern")

In [122]:
stamp+Hour()

Timestamp('2012-03-11 03:30:00-0400', tz='US/Eastern')

In [123]:
stamp = pd.Timestamp("2012-11-04 00:30", tz="US/Eastern")

In [124]:
stamp

Timestamp('2012-11-04 00:30:00-0400', tz='US/Eastern')

In [125]:
stamp+2*Hour()

Timestamp('2012-11-04 01:30:00-0500', tz='US/Eastern')